### ISSUE TITLE
flutterlocation has a health of 96, but apparently it crashes and hasn't been touched since Nov

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub-dev#1077]
URL: https://pub.dartlang.org/packages/location

Not sure how to send signals like "people are reporting this crashes" and "hasn't been updated since Nov", but this plugin probably doesn't warrant a health score of 96.

Is there an admin feature where admins can control the health or downvote?

**Comment by isoos** [comment]
Static analysis has not found any issues. Popularity is `96`, health is `93`, mostly because the formatting and lack of description. Even if we were to run package code (e.g. test), the package has no tests. For all that we can see, this is a popular package with not much risk to use.

Having said that, if a package would do nothing else but to `throw new Exception();` on every method, we may think the same of it, as long as it is popular...

/cc @mit-mit about the user-provided feedback on packages
