### ISSUE TITLE
Use highlight.js and github.css from pkg:dartdoc

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dev#1088]
This is on the way to https://github.com/dart-lang/pub-dartlang-dart/issues/871

Once https://github.com/dart-lang/pub-dartlang-dart/pull/1070 lands, you have access to https://github.com/dart-lang/dartdoc/tree/master/lib/resources

Could look to remove https://github.com/dart-lang/pub-dartlang-dart/tree/master/static/highlight – and just use the content in dartdoc

**Comment by isoos** [comment]
#1070 don't include it as pubspec dependency, it'll be only a `global activate` util. nevertheless, we can and shall adopt the same styles.

**Comment by isoos** [comment]
I've checked, the files in https://github.com/dart-lang/pub-dartlang-dart/tree/master/static/highlight are the same as in dartdoc. Nothing to do this time?

**Comment by kevmoo** [comment]
I was hoping for a package dependency – so it just "happens" – but no biggy.

Figuring out how to align the custom CSS would also be great

**Comment by isoos** [comment]
On thing that I've noticed with the current markdown table issue is that dartdoc uses a lot of styling in their `styles.css` that we may also use, but can't directly, because the rest of the styles are for a full dartdoc page, and not for our package page.

Not sure how much effort we should put in it, but separating some of these reusable styles could work for us.

**Comment by kevmoo** [comment]
Thoughts, @jcollins-g ?

**Comment by jcollins-g** [comment]
No objections to reorganizing our CSS in a way that works better for you.  If you do so though, please check that Flutter in particular still works as they also modify the style.

**Comment by isoos** [comment]
As far as I can tell (checking docs.flutter.io) flutter does not override the `static-assets/styles.css`, it just adds extra `<style>` blocks that does the override, e.g. here:
https://github.com/flutter/flutter/blob/master/dev/tools/dartdoc.dart#L124

My 'split' suggestion would preserve the same semantics that `styles.css` has, but it would contain the rules in two files instead of one, and the dartdoc template would include both.

**Comment by isoos** [comment]
This was done (~ a year ago?).
