### ISSUE TITLE
More clearly report a package's popularity

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/pub-dev#1229]
The pana score is nice.  But it might also be useful to see how popular/not (perhaps graded on a curve?) a package is.

For example, how popular is:
https://pub.dartlang.org/packages/cupertino_icons
compared to:
https://pub.dartlang.org/packages/flutter_local_notifications
?

I'm trying to walk the user journeys of:
- "I'm new to Flutter and looking to learn what packages I should know about"
and/or
- "I'm a package author and would like to understand how popular my package is"

**Comment by isoos** [comment]
The popularity score - which is part of the final "promoted" score - of the former is 100, while the later has 37, which can be seen on the analysis tab.

For the 1st journey, I think the landing page with the most popular package is a good start, maybe an editorial list of packages would also be helpful, but that is certainly not based on score.

For the 2nd journey:
  - Is the score too hidden/subtle?
  - Do we need to have more explanation around it?

**Comment by eseidelGoogle** [comment]
I see, so the popularity score already exists and is graded on a curve?

I guess I was expecting something on the main page page saying "this package is really popular" or similar. 🔥 🔥 But I see now at least some of the data is there.

Maybe there isn't anything to do here at this time.

Maybe I was expecting to see "this is the 337th most popular package, hence your score is 37/100 for popularity".  I can file a separate bug for something like that.

**Comment by isoos** [comment]
I am separating this into two issues:

*First*, it would be nice if we had a quick visual indication of a package's popularity alongside the overall score. Usually if the overall score is high, it is high because a package is both good quality by our current metrics and it is popular (compared to other packages). However there are cases where the package is out of date, yet popular (for example: [bignum](https://pub.dartlang.org/packages/bignum#-readme-tab-), and such icon would make that clear without clicking through to the analysis tab.

<img width="58" alt="screen shot 2018-06-27 at 16 42 32" src="https://user-images.githubusercontent.com/4778111/41981649-b6fa3608-7a29-11e8-9780-18c1cdc3b539.png">

Instead, we could use the fire emoji there:

<img width="53" alt="screen shot 2018-06-27 at 16 45 57" src="https://user-images.githubusercontent.com/4778111/41981672-c1e71f7c-7a29-11e8-9f67-491b71888ce4.png">

@mit-mit: wdyt?

*Second*, we need to update the display of the scores on the analysis tab, and explain better what's going on there and why the score works the way it works.

**Comment by mit-mit** [comment]
I like the fire overlay!

@eseidelGoogle did you make it to the ['score/analysis' tab](https://pub.dartlang.org/packages/flutter_local_notifications#-analysis-tab-), but did not understand the Popularity score shown there, or did you not think the score was clickable and thus did not discover that tab?

**Comment by suburbanworrier** [comment]
I ended up here trying to figure whether Stagehand's popularity score of 37 is accurate?
In terms of a user trying to figure the importance of various parts it wouldn't fare very well with it overall ranking of 67 - I'd likely disregard it in an initial sweep.

Given that Stagehand does the heavy lifting at the start of every(?) ide-created project I would have expected a much, much higher popularity figure (not having the first idea how you collect popularity data).

**Comment by mit-mit** [comment]
I believe we have two separate issues:

1. We don't clearly report the popularity measure for a package on list and detail pages. I'm tilting the current issue to cover that
1. We report only a very indirect popularity measure, and not the raw downloads. That is covered in #2714

**Comment by mit-mit** [comment]
@isoos assigning this to you as I believe the reporting issue is part of the current redesign.

**Comment by jorwan** [comment]
Can I see how many download have it ?

**Comment by iapicca** [comment]
this issue seems to be addressed in this PR
- https://github.com/dart-lang/pub-dev/pull/8126
