### ISSUE TITLE
Use a Dart-only library for archives instead of the 'tar' executable.

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dev#142]
Calling the 'tar' executable makes pub vulnerable to various issues, dealing it with a Dart-only library makes it safer. This library seems to be able to deal with it adequately: https://pub.dartlang.org/packages/archive

**Comment by isoos** [comment]
@nex3 asked for a verification in the pub issue, so I've created a script that can check the uploaded package archives, and indicate if it is unable to parse it for the same use cases that we are doing it with 'tar'.

Here is the current code, not sure if we want to pull it yet:
https://github.com/dart-lang/pub-dartlang-dart/compare/master...isoos:tar_test_archive

I've run it on the dev/staging database, and out of the 23542 PackageVersions there, I've got:
- 23382 valid (99.32%)
- 160 invalid, out of which:
  - 38 download error (may be transient, may be missing in the environment)
  - 63 parse error (**issue in archive**)
  - 57 UTF-8 encoding issue, the file can be read, but the UTF-8 content parsing failed (*may be issue in archive*)
  - 2 other

Couple of options:
- untar and re-package the archives with the dart library
- fix the [archive](https://pub.dartlang.org/packages/archive) library to handle things that it is not able to handle (I don't know whether the author will be available for this)
- de-prioritize the issue

Any thoughts? (/cc @mkustermann, @filiph, @kevmoo)

**Comment by nex3** [comment]
I think fixing the archive library is the right way forward. We'd need to be confident that it was maintained and that any new bugs would be fixed anyway before we started using it.

**Comment by isoos** [comment]
To track the archive bug: https://github.com/brendan-duncan/archive/issues/34

**Comment by mkustermann** [comment]
I think we should de-prioritize this issue for a various of reasons:

  * So far almost all issues we have had with tar was on the client side: The pub client runs on different OSes and therefore is exposed to different versions/variants of tar, which caused issues (partially due to the pub client using special flags/options). The server has not had any serious issues regarding `tar` as far as I can recall atm. So using a dart-only implementation on the client seems much more important than on the server.

  * The statement that `'tar' executable makes pub vulnerable to various issues` seems more of a general statement that dart-only code is safer than native code - which I agree with. Though the [package:archive](https://pub.dartlang.org/packages/archive) it is an external package and not under our control. So there is as well the possibility of upgrading to a malicious package (e.g. due to the package being compromised) - even with pinning we should sanitize the code.

  * If we had a high-quality implementation in Dart, we could use, I would be strongly in favor of switching to it. Unfortunately I think [package:archive](https://pub.dartlang.org/packages/archive) is not there yet. Not only (as demonstrated above) is it incomplete in terms of functionality and not battle tested, it has other disadvantages: When I started to write the server in Dart I looked briefly at the package, but one thing came up as quite an issue: Back then (and I suspect it is still the case) it kept all data in memory. This might not seem like a big issue, but we have a maximum upload size of 100 MB. This means with very few requests one could cause the server to crash due to OOM.

**Comment by nex3** [comment]
@isoos Want to move discussion to dart-lang/pub#1602? Most of the issues Martin raised with the quality of the archive package still apply on the client, but we have a more urgent need for a better solution there too.

**Comment by brendan-duncan** [comment]
The error with the archive package is due to it not supporting the tar PAX extension. I will be adding that support shortly.

If you would like it to support disk streaming for archives to avoid memory issues, feel free to submit an issue.

**Comment by isoos** [comment]
Thanks @brendan-duncan, I've filed https://github.com/brendan-duncan/archive/issues/35

**Comment by isoos** [comment]
An update on the tar parsing issue: the archive-1.0.29 release fixed the extraction issue on the files in pub staging. The UTF-8 parsing exception is still there, but manual verification confirmed that the  files in question do have invalid Unicode characters. I'll do further experimenting how to treat those special cases (because `new Utf8Decoder(allowMalformed: true)` throws an exception on them).

**Comment by nex3** [comment]
> because `new Utf8Decoder(allowMalformed: true)` throws an exception on them

This sounds like a bug... can you file an issue against the SDK?

**Comment by isoos** [comment]
I've double-checked, and my claim about `allowMalformed: true` was wrong. The archive extraction and the UTF8 decoding (with `allowMalformed: true`) was working all right. It was our current `readTarballFile` method that threw the exception, on parsing the output of the `tar` command.

**Comment by isoos** [comment]
I've also validated the rest of the issues on the staging database, `archive` works OK, `Utf8Decoder(allowMalformed: true)` works OK, I think we are good to go with the `archive` package. The only concern is that it needs to read everything into memory, so I'd wait until https://github.com/brendan-duncan/archive/issues/35 gets fixed and published.

**Comment by brendan-duncan** [comment]
I am still working on https://github.com/brendan-duncan/archive/issues/35,
but might be delayed if I can't get to wrapping it up before my vacation. I
have much of the file streaming working now but have a few remaining tasks.

**Comment by isoos** [comment]
Closing this issue in favor of #4440
