### ISSUE TITLE
Consider making script.dart smaller and maybe async

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2197]
I'm not sure if we can make it async... It would be nice if it could.

But we should be able to make it smaller, maybe there's some dart2js options we can tweak.
Accoriding to chrome dev tools it's currently 153kb, while the Dart source is only 13kb.
We could rewrite it to javascript, try to avoid some of it, or tweak dart2js.

According to devtools, my browser spends about 98ms parsing it... which seems a bit expensive for hooking up a few event handlers.

**Comment by isoos** [comment]
> Accoriding to chrome dev tools it's currently 153kb, while the Dart source is only 13kb.
> We could rewrite it to javascript, try to avoid some of it, or tweak dart2js.

Or... maybe file a tracking bug for dart2js to do better in minifying the results.

**Comment by isoos** [comment]
> Accoriding to chrome dev tools it's currently 153kb, while the Dart source is only 13kb.

I was interested to lookup a historical data point: in #1393 around a year ago it was 146 kb. The script did change since then, so it may not be indicative of anything.

gzipped size is 45 kb, which is not too bad. If we were to rewrite it with jquery + js, I doubt that it would be much less than 35-40kb, as jQuery gzipped is 30k.

> According to devtools, my browser spends about 98ms parsing it... which seems a bit expensive for hooking up a few event handlers.

But it is not 98ms for the event handlers, it is 98ms to parse the source + running it, isn't it? The code contains enough complexity that I doubt that a significant speedup could be achieved even with plain JS, or with jQuery. And to be honest, even if we would reduce it to 0ms, I doubt that it is a priority for now.

**Comment by jonasfj** [comment]
Why would we need jquery? we could probably do it plain js...

But I agree this is low priority... it might not even be worth optimizing.

**Comment by isoos** [comment]
> Why would we need jquery? we could probably do it plain js...

The script's code is mostly trivial, but it gets into parts that are non-trivial in plain JS, so either a generic library like jQuery or re-implementing parts of jQuery will be required.

**Comment by isoos** [comment]
Since we are going to implement some of the admin stuff in JS, I think it is not really relevant to keep this issue open.
