### ISSUE TITLE
Merge stylesheets to a single css file

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2224]
We currently have 3 stylesheets:
```
/static/highlight/github.css
/static/css/github-markdown.css
/static/css/style.css
```
Merging them with scss could improve load time a little... Given that these are cached, it probably won't have much impact, but improve first load is always nice.

If we include source maps and ship original source along side with license headers (in the original source), then this might be okay. As opening the CSS file in the browser should show you the original source with license headers... I highly doubt anyone will mind this...

If we want to be perfectly safe, we could perhaps do a re-implementation of these styles too..

**Comment by isoos** [comment]
This is slightly non-trivial:
- sass `@import` can be used only if the file has `.scss` extension or if it is a symlink, otherwise it will emit `@import "path";` in the output, and does not do inlining.
- dartdoc customization uses the `github-markdown.css` as a separately included content, and we cannot rename it to scss (or we'll need to have another css compilation for it).

The next steps could be:
- Include `github-markdown.css` in `package:dartdoc`, so that we don't need to customize ourselves.
- Rename our CSS files to scss, and change the style.scss to include them.

**Comment by jonasfj** [comment]
See: https://sass-lang.com/documentation/at-rules/import#importing-css

Just don't include the `.css` extension it and should work :)

**Comment by isoos** [comment]
I've tried that, it still did not inline. A stackoverflow answer pointed out that only the symlink works if you don't want to change the extension.

**Comment by sigurdm** [comment]
Done
