### ISSUE TITLE
Tell users to setup pedantic when showing analysis results

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2373]
When looking at "Health suggestions" from analysis, we should be informing the user that the package isn't satisfying `pedantic` lints. And we should link to how to setup these lints locally using:

 * `https://dart.dev/guides/language/analysis-options#default-google-rules-pedantic`

## Screenshot

![image](https://user-images.githubusercontent.com/149732/59602455-1420c000-9107-11e9-8f63-b5a220330970.png)

**Comment by jonasfj** [comment]
The only hard part is we should only show this information when relevant, and we should not show it for each bullet point.

**Comment by isoos** [comment]
I'm not sure how easy it is to identify whether an issue is from `pedantic` or `dartanalyzer` defaults. It gets much more complex if it is in a bulk report mode.

Another aspect: ideally, we want to have all of our instructions in a single place (which is right now the `/help` page). Maybe we should first improve that, and do more proponent linking from the analysis tab to the relevant help section?

**Comment by jonasfj** [comment]
Upon checking the analyser does show where things come from, see:
```
dartanalyzer --format machine .
INFO|HINT|UNUSED_LOCAL_VARIABLE|/source/dart-neats/neat_periodic_task/lib/neat_periodic_task.dart|171|11|7|The value of the local variable 'cheese' isn't used.
```

I think `UNUSED_LOCAL_VARIABLE` is a good indicator that they are from lints... probably `HINT` means that it's a linter-thing -- that would be my guess (we could try it out).

**Comment by jamesderlin** [comment]
Does pub.dev use `package:pedantic`'s `analysis_options.yaml` when performing analysis on a package?   My understanding was that `package:pedantic`'s options were fairly tailored to Google's internal style and that some of its options aren't necessarily expected to be adopted externally.

See https://stackoverflow.com/questions/62163094/pub-dev-static-analyzer-emits-additional-errors, where a user isn't able to perform the same analysis locally because pub.dev uses different analysis options.

It would be nice if pub.dev just published whatever `analysis_options.yaml` file it's using (perhaps linked to from a package's analysis tab).

**Comment by sigurdm** [comment]
I think we do this
