### ISSUE TITLE
Support latest dependencies. (-5 points)

### ISSUE THREAD

**Issue by felangel** [dart-lang/pub-dev#2380]
URL: https://pub.dev/packages/path_provider#-analysis-tab-

Looks like every flutter package is affected by an issue where 5 points are deducted from their score due to not supporting the latest version of 1 dependency.

<img width="686" alt="Screen Shot 2019-06-18 at 11 17 40 PM" src="https://user-images.githubusercontent.com/8855632/59736488-710f9980-921f-11e9-9d57-88b885283d86.png">

I'm guessing it has to do with the fact that the flutter version is resolved to `0.0.0`.

**Comment by jonasfj** [comment]
Nice catch, but yeah there seems to be something odd here.

**Comment by isoos** [comment]
On the linked `path_provider` package it is because of `meta`: the resolved version is `1.1.6`, while the available version is `1.1.7`.

It looks like the old issue that Flutter fixes every dependency is blocking us with such checks:
https://github.com/flutter/flutter/blob/master/packages/flutter_goldens/pubspec.yaml

At minimum we should tune it down and not report it on transitive dependencies.

**Comment by jonasfj** [comment]
Yeah, let's only reduce the score if direct dependencies are outdated. Transitive dependencies is hard to control.

We could even go a step further an only reduce score if the constraint in the pubspec doesn't allow the latest version for all direct dependencies.

**Comment by isoos** [comment]
The fix has been deployed.

**Comment by felangel** [comment]
@isoos @jonasfj I am seeing the same issue again. Looks like a regression? 🙁

**Comment by isoos** [comment]
Sorry for the ever-changing analysis, but we have a temporary traffic migration rollback to a previous pub site version due to unrelated causes. This particular bug was fixed and early next week we'll be again on the latest pub site version, the penalty will go away.

**Comment by felangel** [comment]
@isoos any updates on this? If there's anything I can do to help please let me know.

**Comment by isoos** [comment]
@felangel thanks for reporting back in this, looks like we have an edge case that was not covered before. It seems that we need to re-structure the constraint check, as the current logic can't cover your case.

**Comment by felangel** [comment]
@isoos any updates on this? I’m more than happy to help open a PR. Do you have any pointers/suggestions for how to resolve the issue? Thanks 🙏

**Comment by isoos** [comment]
It is not forgotten, but we are working on a feature that is a higher priority and this was pushed back on the priority list. If you want to have a take on it, this is the code that needs to changed:
https://github.com/dart-lang/pana/blob/master/lib/src/maintenance.dart#L538-L556

However, the larger part of the PR will be to also modify the tests. If you want to do it, let me know, I'll assist you.

**Comment by jakemac53** [comment]
I believe the `dwds` packages is being affected by this as well https://pub.dev/packages/dwds#-analysis-tab-.

It is deducting score because of `devtools` not resolving to the latest version (0.1.5) but that version is allowed by the pubspec.

It is very common that some (even transitive) dependency could be restricting the version solve for some immediate dependency. Packages should not be punished for this as its out of their control.

IMO it should only be checking whether the explicit constraint in the pubspec allows the latest version.

**Comment by jonasfj** [comment]
> IMO it should only be checking whether the explicit constraint in the pubspec allows the latest version.

Yes, this issue is tracked here: https://github.com/dart-lang/pana/issues/551

**Comment by isoos** [comment]
The pana fix was deployed a while ago.
