### ISSUE TITLE
Duplicate packages (copying) autocomplete_textfield

### ISSUE THREAD

**Issue by felixlucien** [dart-lang/pub-dev#2389]
Hey, it seems that someone has blatantly copied my package (autocomplete_textfield) with the new name autocomplete_textfield_modified from the uploader habib23me@gmail.com. I'm even still listed as the author. Could this possibly be removed as it is just a clone package of mine?
(Is this the right place to submit this kind of issue? I couldn't find any sort of contact staff page). Thanks, Felix McCuaig.

**Comment by jonasfj** [comment]
> Is this the right place to submit this kind of issue?

Yes, for now it is, we're working on improving these processes.

----

I imagine that someone patched your package, and created a fork instead of sending a pull-request on github. Let's assume good intentions on all parties here :)

I guess it's not ideal that the repository links to your repository and not the fork. As this could lead downstream users to file issues against `autocomplete_textfield_modified` in the repository for `autocomplete_textfield`.

Note. in calling the package `autocomplete_textfield_modified` it's certainly very clear that this is a fork. It's not pretty, but it's better than having dependency on a git repository (which we are planning to forbid, see https://github.com/dart-lang/sdk/issues/36765 -- only for published packages though).

I'm not entirely sure what our policy on this is... @mit-mit ? But assuming there is nothing illegal going on, we strongly prefer "package deletion" or "package discontinue" requests to originate from a person listed as _uploader_ a given package.

Ideally, everybody would be happy if changes were upstreamed... and the author of `autocomplete_textfield_modified` filed a "discontinue package" request.
