### ISSUE TITLE
Maintenance score of all Flutter plugins decreased because of meta

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [dart-lang/pub-dev#2452]
Currently, every package that depends on `flutter` has -5 maintenance points as the `meta` package in the Flutter SDK is not up to date ([example](https://pub.dev/packages/path_provider#-analysis-tab-)).

This has been the case for at least a few weeks now and I am suprised that I could not find anything about it anywhere here nor anywhere else.

It does not seem right to me or is this intended?

**Comment by isoos** [comment]
It was reported in https://github.com/dart-lang/pub-dev/issues/2380 and fixed in https://github.com/dart-lang/pana/pull/540. However, due to unrelated reasons, we did not have a stable release since then, and the symptom is still pending on the pub site. Apologies for the delay, we are planning to release a new version on Monday, it should fix it.
