### ISSUE TITLE
searching for validator returns weird results

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/pub-dev#2622]
https://pub.dev/packages?q=validator

4: flutter_form_builder
5: material_search
6: groovin_widgets
7: aqueduct

but doesn't list string_validator.
https://pub.dev/packages/string_validator
80 score points

Maybe name matching should always comes first?

**Comment by isoos** [comment]
`flutter_form_builder` has `validate` and similar words in the readme, but `material_search`, `groovin_widgets` and `aqueduct` have it only in their public API. I agree, `string_validator` should be presented more in the front of the list, probably by:

- reducing the weight of API matches and increasing the name matches
- reducing the weight of popularity in the final order

**Comment by jonasfj** [comment]
Tweaking search is always tricky, but thanks for highlighting more cases we can investigate.

**Comment by isoos** [comment]
I did a bit of debugging, and the following scoring breakdown happens:

Name index:
```
string_validator: 0.989
flutter_form_builder: 0.000
```

Description index:
```
string_validator:  0.354
flutter_form_builder: 0.352
```

Readme index:
```
string_validator:  0.853
flutter_form_builder: 0.712
```

API index:
```
string_validator: 0.908
flutter_form_builder: 0.911
```

Overall text score (the max of the above):
```
string_validator: 0.989
flutter_form_builder: 0.911
```

Overall score multiplier (with current popularity values):
```
string_validator: (0.82*0.7 + 0.3) = 0.874
flutter_form_builder: (0.98*0.7 + 0.3) = 0.986
```

Search result score (if nothing else, e.g. platform specificity is considered):
```
string_validator: 0.989 * (0.82*0.7 + 0.3) = 0.864
flutter_form_builder: 0.911 * (0.98*0.7 + 0.3) = 0.898
```

In this case tuning down the API weight seems to be the more appropriate measure, as the popularity tuning doesn't change the order even if we did 50-50% instead of 70-30%.

**Comment by isoos** [comment]
Since the original issue report, we've deployed a few tweaks on search, and now searching for `validator` seems to yield better results, including `string_validator`.
