### ISSUE TITLE
Search result performance has degraded in the past 6 weeks

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#2705]
The 95% percentile seems significantly worse.

We should investigate and find out what changed.

**Comment by isoos** [comment]
Top candidate for root cause in the timeframe: https://github.com/dart-lang/pub-dev/pull/2632 (makes the n-gram similarity calculation longer).

I'll do a rough breakdown of timings what happens during search with one of the recent long-running queries: `PlatformException`. We had a few outliers like one with 20+ words, but most of the longer running ones are just 2-3 words like this one (we do split it to separate words too).

**Comment by isoos** [comment]
- Of the core text search part, 85% of the time is spent in `TokenIndex.lookupTokens`
- Of that,
  - 34.5% is in ngram parsing (`ngrams` in `text_utils.dart`)
  - 57.0% is in `_ngramSimilarity` (of which #2632 did change)

I believe that the root cause of the regression was the change from simple int multiplication to floating point math in the scoring. I also have a fix that uses pre-computed values for that operation.
