### ISSUE TITLE
Version solving failed when using different paths for the same library version

### ISSUE THREAD

**Issue by andyalbert** [dart-lang/pub-dev#2732]
I'm building an application which includes a module named X, and also, another module named Y which depends on X but on a different path.

Both of the 2 X's are of the same version, however, when I try to run pub get in the directory, I got the following error:
`Because every version of Y from path depends on X from path ..\Y\X and library depends on X from path ..\X, Y from path is forbidden.
So, because library depends on Y from path, version solving failed.
`

**Comment by jonasfj** [comment]
This seems like an issue in the pub client, see: http://github.com/dart-lang/pub

On topic: I think you can solve this by using absolute paths...  or play with `dependency_overrides`:
https://dart.dev/tools/pub/dependencies#dependency-overrides

It's possible that the `pub` doesn't resolve path dependencies into absolute paths, and thus, can't see that two relative paths for the same package are the same path.
But we need a minimal proof of concept to show this..

And even if this is the case, and it can be fixed in the pub client, we might want to think about what the implications are.

A good first step would be to build a gist / tarball or repository with multiple packages and demonstrate how this is a problem. The search the `pub` issue tracker for similar issues. Maybe this has been discussed before and resolved because of some negative implications (I don't have a complete historical insights here).
