### ISSUE TITLE
Please Consider adding a server Tab.

### ISSUE THREAD

**Issue by G5Becks** [dart-lang/pub-dev#2927]
Hi, I am creating this issue in the hopes that you all would consider adding a server Tab to pub.dev. Currently, it is arranged as 

> Flutter, Web, All

I honestly don't quite understand the reasoning behind the way that this is organized. If the package is not for Flutter or Web, then it's for the server. I understand that Dart is being pushed as a client-side targeted language, but there are many people who write servers, cli apps, and other utilities in dart and trying to find packages specific to the server is currently made difficult by the fact that when I search for them, the only way to filter is to click the "All" tab, which includes all the flutter and web stuff that is not useable in this context.

Hopefully, this change can be taken into consideration.

Thanks.

**Comment by isoos** [comment]
We did have a /server endpoint once, but it turned out to be difficult to classify it properly. Some examples can be found here: https://github.com/dart-lang/pub-dev/issues/858

We hope to expand the classification and tag the "server", "build" and other CLI-related platforms correctly in the future.

**Comment by G5Becks** [comment]
Thanks for the response,  I can see that this might not be as simple as I'd imagined considering how things a dart package might be used for. Glad to hear that it's something being taken into consideration though.
