### ISSUE TITLE
http.get(url) always responds with null

### ISSUE THREAD

**Issue by jonhygg99** [dart-lang/pub-dev#2984]
URL: https://pub.dev/packages/http#-example-tab-

Hello, I try with different examples and I always get the same response, null. I uninstall flutter and dart in Android Studio but have the same issue. I debug it and always is null. The behavior is that when goes to the line of http.get after the response does like an exit of the function. 
I use this version:  http: ^0.12.0+2
I really don't know what else to try.
Any suggestion?

**Comment by isoos** [comment]
@jonhygg99: This tracker is for the pub.dev site only, and not for individual packages, I'll close this issue here. Please use the `http` package's own issue tracker and file a new issue: https://github.com/dart-lang/http/issues

A suggestion: please also provide more context of your code and how you are calling `http.get`.
