### ISSUE TITLE
Avoid using innerHtml

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3045]
I only saw us using it in:
https://github.com/dart-lang/pub-dev/blob/400f418d6bbac7142334dfcbb9cf24c596ae9a51/pkg/web_app/lib/src/search.dart#L37

Which seems unnecessary, let's remove that, just for hygiene, and maybe even write a test that greps the source to check that we're not using `innerHtml`.

I know it's not the end of the world to use it, if used correctly, but if possible it's nice to avoid :)

**Comment by jonasfj** [comment]
@isoos, is this crazy?

**Comment by isoos** [comment]
It seems to be easy to remove it, but it also seems arbitrary in this case, as it does not depend on user input. I think it may be easier to remove it then argue about it :)

**Comment by isoos** [comment]
Hm, looking at the code, it may be better if we'd generate the sort control on the server side. It got to the client-side because if the client has no JS enabled, there was no point of displaying the control, however, we have now plenty of controls that behave the same way, it would be just better to generate this on the server, and only wire the required event on the client.

**Comment by jonasfj** [comment]
> Hm, looking at the code, it may be better if we'd generate the sort control on the server side.

Seems like a neat cleanup thing :)

I agree that this instance is completely harmless. But if we remove it we could contemplate adding a test that greps for `innerHtml` to prevent us from using it..
