### ISSUE TITLE
Http ImageUpload via POST Method Error : FormatException: Unexpected end of input (at character 1) ?

### ISSUE THREAD

**Issue by MungaraJay** [dart-lang/pub-dev#3060]
I need to upload an image to server with header, body and token using http package.

```
http.MultipartRequest imageUploadRequest = http.MultipartRequest('POST', Uri.parse(BASE_URL));

imageUploadRequest.headers["Authorization"] = "bearer ${token}";
imageUploadRequest.headers["Content-Type"] = "multipart/form-data";

imageUploadRequest.fields["testID"] = widget.testID;
imageUploadRequest.fields["ContentType"] = "application/json";
imageUploadRequest.fields["ContentDisposition"] = "form-data";

final file = await http.MultipartFile.fromPath('file', image.path);
imageUploadRequest.files.add(file);

print("imageRequest.headers : ${imageUploadRequest.headers}");
// Log-> imageRequest.headers : {Authorization: bearer eyJhbGciOiJSUzIlY3VyZXRva2VuLmdvb2dsZS5jb20vdXBwZWQtOWVjYTgiLCJhdWQiOiJ1YrJHsNdkYQDGNqCaPkooE6Ht00e-09TXnbH19-sfD5buR-tt0P_RmizY0Q, Content-Type: multipart/form-data}

print("imageRequest.fields : ${imageUploadRequest.fields}");
// Log -> imageRequest.fields : {testID: iL7r9ehjwv3HlmdC, ContentType: application/json, ContentDisposition: form-data,}

print("imageRequest.files : ${imageUploadRequest.files}");
//Log -> imageRequest.files : [Instance of 'MultipartFile']

final streamedResponse = await imageUploadRequest.send();
print("streamedResponse.statusCode : ${streamedResponse.statusCode}");
// Log-> streamedResponse.statusCode : 307

print("streamedResponse.headers : ${streamedResponse.headers}");
// Log-> streamedResponse.headers : streamedResponse.headers : {x-powered-by: ASP.NET, location: https://api.test.me/image, date: Sat, 23 Nov 2019 05:01:48 GMT, transfer-encoding: chunked, server: Microsoft-IIS/10.0}

final MapString, dynamic responseData = json.decode(response.body);
print("statusCode : ${response.statusCode}");
// Log-> statusCode : 307

print("headers : ${response.headers}");
// Log-> headers : streamedResponse.headers : {x-powered-by: ASP.NET, location: https://api.test.me/image, date: Sat, 23 Nov 2019 05:01:48 GMT, transfer-encoding: chunked, server: Microsoft-IIS/10.0}

```

But, I got the following error "Error : FormatException: Unexpected end of input (at character 1)" with status code 307.

Can anyone please tell me what is the problem?

My headers, fields passed from multipart request are not matching with the returned response from api.

This code is working fine in my another application with multipart file upload.

Thanks.

**Comment by isoos** [comment]
@MungaraJay: this tracker is for the pub.dev site and related issues. If you are using a Flutter plugin, please use the package's issue tracker for reporting problems.

Having said that, you probably need to track down what caused the `FormatException` (e.g. what the server replied and how you wanted to process it).

**Comment by MungaraJay** [comment]
@isoos I am using http package for uploading image to server. Above parameters are working fine while testing with postman. No issues found. While, using it from the app using above code gives me the FormatException.

**Comment by BaderEddineOuaich** [comment]
<h3>This can be caused by the Mime Type of the file. try this:</h3>
</pre>
<strong> 
// Find the mime type of the selected file by looking at the header bytes of the file<br>
final mimeTypeData = lookupMimeType(image.path, headerBytes: [0xFF, 0xD8]).split('/');</strong><br><br>
http.MultipartRequest imageUploadRequest = http.MultipartRequest('POST', Uri.parse(BASE_URL));

imageUploadRequest.headers["Authorization"] = "bearer ${token}";
imageUploadRequest.headers["Content-Type"] = "multipart/form-data";

imageUploadRequest.fields["testID"] = widget.testID;
imageUploadRequest.fields["ContentType"] = "application/json";
imageUploadRequest.fields["ContentDisposition"] = "form-data";


<strong>
// Attach the file in the request<br>
final file = await http.MultipartFile.fromPath('image', image.path, contentType: MediaType(mimeTypeData[0], mimeTypeData[1]));</strong><br><br>
imageUploadRequest.files.add(file);
print("imageRequest.headers : ${imageUploadRequest.headers}");

print("imageRequest.fields : ${imageUploadRequest.fields}");

print("imageRequest.files : ${imageUploadRequest.files}");
final streamedResponse = await imageUploadRequest.send();
print("streamedResponse.statusCode : ${streamedResponse.statusCode}");
print("streamedResponse.headers : ${streamedResponse.headers}");
final MapString, dynamic responseData = json.decode(response.body);
print("statusCode : ${response.statusCode}");
print("headers : ${response.headers}");

</pre>

**Comment by BaderEddineOuaich** [comment]
This can be caused by the Mime Type of the file. try this:
Add [Mime Package](https://pub.dev/packages/mime)
<strong>
// Find the mime type of the selected file by looking at the header bytes of the file
final mimeTypeData = lookupMimeType(image.path, headerBytes: [0xFF, 0xD8]).split('/');
</strong>

http.MultipartRequest imageUploadRequest = http.MultipartRequest('POST', Uri.parse(BASE_URL));

imageUploadRequest.headers["Authorization"] = "bearer ${token}";
imageUploadRequest.headers["Content-Type"] = "multipart/form-data";

imageUploadRequest.fields["testID"] = widget.testID;
imageUploadRequest.fields["ContentType"] = "application/json";
imageUploadRequest.fields["ContentDisposition"] = "form-data";
<strong>
// Attach the file in the request
final file = await http.MultipartFile.fromPath('image', image.path, contentType: MediaType(mimeTypeData[0], mimeTypeData[1]));
</strong>

imageUploadRequest.files.add(file); print("imageRequest.headers : ${imageUploadRequest.headers}");

print("imageRequest.fields : ${imageUploadRequest.fields}");

print("imageRequest.files : ${imageUploadRequest.files}");
final streamedResponse = await imageUploadRequest.send();
print("streamedResponse.statusCode : ${streamedResponse.statusCode}");
print("streamedResponse.headers : ${streamedResponse.headers}");
final MapString, dynamic responseData = json.decode(response.body);
print("statusCode : ${response.statusCode}");
print("headers : ${response.headers}");
