### ISSUE TITLE
i cant find a single package which can convert pdf to string.

### ISSUE THREAD

**Issue by solow-crypt** [dart-lang/pub-dev#3126]
URL: https://pub.dev/help

I want to make an app which can extract raw text of any pdf.

**Comment by isoos** [comment]
@solow-crypt: this issue tracker is for the pub.dev site (e.g. if you experience operational issues or have feature requests). (I'm closing the issue because of that.)

I have looked for similar packages at one point, a small things that may help: [Apache Tika](https://tika.apache.org/) is a nice Java-based library to extract content, and they have a server mode, which receives the pdf document and replies with its content. [package:tika_client](https://pub.dev/packages/tika_client) can help you accessing it.

Other than that, it seem there are pdf viewers libraries for Flutter, and a generic writer, but not a parser yet.
