### ISSUE TITLE
Support more Target platforms

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/pub-dev#3188]
With Flutter supporting now officially more than iOS and Android, it would be really great if:

* The search filter would list also the target platforms
* Show all supported platform on the search result list.

Cheers
Thomas

**Comment by isoos** [comment]
These are already present on SDK-specific package listing pages, e.g.:

<img width="735" alt="Screen Shot 2019-12-18 at 21 06 00" src="https://user-images.githubusercontent.com/4778111/71119354-40161e80-21da-11ea-92f4-f88f720b8e91.png">

However, if you use 'Any' (no SDK filtering), we fall back to the SDK-support only, because otherwise we would display way too many tags (esp. if there would be more in the future).

Would there be something that we could add to make this better?

**Comment by escamoteur** [comment]
Ah, great, I wasn't aware that the filter changes if you select Flutter. Are you already supporting desktop platforms too?

**Comment by isoos** [comment]
> Are you already supporting desktop platforms too?

We are adding support for them both on the analysis and the UI part of the site. (Some data is already there, but other parts are missing.)

**Comment by YazeedAlKhalaf** [comment]
Any Updates? All Desktop Platforms are now in the alpha stage. It would be great to have a filter for Windows, macOS, and Linux. And have the supported desktop platforms displayed in the package info.

Example Image: (https://i.imgur.com/K0kPwh4.png)
<img src="https://i.imgur.com/K0kPwh4.png" />

**Comment by isoos** [comment]
> It would be great to have a filter for Windows, macOS, and Linux.

There is an advanced search filter when you select Flutter SDK in the package listing for these:
https://pub.dev/flutter/packages?q=&platform=macos

**Comment by YazeedAlKhalaf** [comment]
Okay, half of the work id done! 🚀

Now we need to add it in the package info page, I think it is an easy fix 🤔.

**Comment by isoos** [comment]
This has been implemented for a while, closing the issue.
