### ISSUE TITLE
Archive Pubs

### ISSUE THREAD

**Issue by amreniouinnovent** [dart-lang/pub-dev#3259]
URL: https://pub.dev/packages/dart_ping

I found this library and I tried to check the GitHub code but unfortunately, it is deleted.
I wonder if google could archive the original code if the user deleted it?

**Comment by isoos** [comment]
@amreniouinnovent: You can click on the "Versions" tab ([link](https://pub.dev/packages/dart_ping/versions)) and select the archive icon for the specific version. This is the package archive with the code that was uploaded to pub, and not the mirror of the git repository (which we don't archive). Would there be a use case where a git mirror would be useful for you instead of this archive?

**Comment by amreniouinnovent** [comment]
@isoos Yes, I didn't know about it.
Google hosts thousands of repositories already. That's great so we will not have broken libraries like 'npm left pad'
