### ISSUE TITLE
Make it easier for me to copy-paste the package name + version for use in pubspec.yaml

### ISSUE THREAD

**Issue by bean5** [dart-lang/pub-dev#3336]
**Expected**
When copying the package name _and_ the version, a visible/hidden `:` comes with it.

![after](https://user-images.githubusercontent.com/2052646/74676257-d632da80-5172-11ea-8f49-54f70b424676.png)

**Actual**
No helpful `:`, which means I paste it into pubspec.yaml and have to edit it.

![before](https://user-images.githubusercontent.com/2052646/74676253-d3d08080-5172-11ea-80aa-f861fc64d207.png)

**Comment by isoos** [comment]
Maybe we could add `^` too, e.g. `uuid: ^2.0.4`?

**Comment by bean5** [comment]
Well, I don't think we want the page to include that by default, which means we'd want a dropdown with various options for easy copy-paste. Something like Github:

![dropdown options with copy to clipboard](https://user-images.githubusercontent.com/2052646/74688645-61bd6300-5195-11ea-8607-565ca711280f.png)

Perhaps something like this, but less ugly:
![dropdown options with copy to clipboard](https://user-images.githubusercontent.com/2052646/74688900-4bfc6d80-5196-11ea-9236-7d38fae75cd1.png)

**Aside:** I think it is a bit overkill. I just wanted to be a little lazier. Not maximum lazy.

**Comment by jonasfj** [comment]
I was secretly hoping we would one day find time to do a `pub add <package>` command, and insert a thing like: `$ pub add uuid` in the top right corner...

**Comment by craigomac** [comment]
As requested by @bean5, I enclose the suggestion I made for this in #3564: 
![image](https://user-images.githubusercontent.com/6972172/81469521-8f8ad480-91e5-11ea-81dd-3e5bd00304e4.png)

**Comment by lukas-h** [comment]
<img width="257" alt="Screenshot 2020-08-03 at 00 38 02" src="https://user-images.githubusercontent.com/10634693/89380768-613f6700-d6f8-11ea-9ead-c6af119bed38.png">

reuploading image from #3902

**Comment by pedromassango** [comment]
Better to implement the suggestion on https://github.com/dart-lang/pub-dev/issues/3336#issuecomment-626133978 it is less confusing.

**Comment by miquelbeltran** [comment]
I understand why there's a need from more experienced devs to have something like this, but I think that this will let to beginners to make two mistakes:

-  to use "exact" versions rather than "within" versions 
i.e. using `package: x.y.z` instead of `package: ^x.y.z`
- to skip required installation steps.

Some packages require extra steps when installing, adding it to the title will cause more beginner developers to skip the important extra steps, leading to more support issues reported for not following them.

There's already an "Installing" section in pub.dev that contains the install instructions, but these are problematic too, because they are auto-generated and miss the extra required steps that are usually listed in the README.md. A usual problem is developers pasting the `package: version` part in the `dependencies:` instead of in `dev_dependencies` or missing some changes that need to be added in the platform project part.

**Comment by orestesgaolin** [comment]
Seems like it's already available
![image](https://user-images.githubusercontent.com/16854239/98939034-18623000-24e9-11eb-8fe7-1fd2b9a63327.png)

**Comment by isoos** [comment]
Yes, closing this issue. Feel free to open new issues for improvements (some are already in the pipeline).

**Comment by pedromassangocode** [comment]
Just filled https://github.com/dart-lang/pub-dev/issues/4244 for some improvements.
