### ISSUE TITLE
Deleting a package version should rerun analysis

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dev#3344]
URL: https://pub.dev/packages/analyzer#-analysis-tab-

v2 of `package_config` was deleted, but there are still ghosts of it around.

See pkg:analyzer, for instance.

![Screen Shot 2020-02-18 at 2 35 13 PM](https://user-images.githubusercontent.com/17034/74784077-f7bbc100-525b-11ea-8db9-5ad5b54c271c.png)

**Comment by jonasfj** [comment]
We do this when a new version is uploaded, I think it's fine to do when deleting a package version too.


Though analysis with rerun within a month regardless, and it's very rare that we unpublish packages, so maybe this is not so important.

Besides, even if we do this, it'll always be a best effort re-analysis of packages that depends on a given package. Because the transitive set can be huge.

**Comment by isoos** [comment]
Note: an analysis can be triggered manually via the following tool:
```
dart bin/tools/notify_service.dart analyzer [pkg] [version]
```

**Comment by kevmoo** [comment]
Good to know!

**Comment by jonasfj** [comment]
Discussed this in triage, and given the low volume of package deletions, we're thinking we'll never get around to prioritize this.
