### ISSUE TITLE
Manage invite/remove uploader from package admin tab

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3381]
This is only relevant for packages that doesn't have a publisher.

If we implement this we can remove the `pub uploader` CLI command. 

This also reduces the API surface between `pub` and `pub.dev`, this is as it makes it more feasible to implement 3rd party pub servers. The simpler the API the better. One could easily imagine a different pub server having a vastly different way to manager user permissions.

@mit-mit, any concerns?

**Comment by sigurdm** [comment]
Only question is if there are people adding uploaders programatically.
I guess that is fairly rare though.

**Comment by isoos** [comment]
> Only question is if there are people adding uploaders programatically.

The add operation is not immediate, we are sending out an invite, which must be clicked. I don't see it happening too often. I can imagine that if you decide to hand over all of your package development to somebody else, this could come handy, but otherwise it is not a common use case, but for that, maybe publishers are a better answer.

Nevertheless, we'll still have the API endpoint (the current one or a new for the UI), and we can probably provide a one-off help how to use that programatically.
