### ISSUE TITLE
Fix /api/packages/<package>/versions/<version>.tar.gz

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dev#3427]
This seems to be an unused API call, because it is not working for a while now. The api generator parses the version pattern to include the `.tar.gz` postfix in the `version`, making version pattern check to fail.

We should:
- fix the API generator
- maybe remove this API if we are not going to use it?

**Comment by jonasfj** [comment]
Ah, we never hit:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/frontend/handlers/pubapi.dart#L50-L52

because we always match this first:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/frontend/handlers/pubapi.dart#L40-L46

In practice it doesn't matter... but, well, maybe it matters a little :) hehe

I think we should write this as:
```dart
@EndPoint.get('/api/packages/<package>/versions/<version|[^ ]+(?:\.tar\.gz)>')
```

Checkout: https://pub.dev/documentation/shelf_router/latest/shelf_router/Router-class.html
The syntax is `<param|regex>` for giving custom regular expressions.

But this raises a different problem. `1.0.0-dev.tar.gz` is a legitimate semver version number.
You could totally publish a package that has `version: "1.0.0-dev.tar.gz"`, but we would have problems serving it -- because we can't tell if you're requesting the tarball for version `1.0.0-dev` or inspecting the pubspec for version `1.0.0-dev.tar.gz` :see_no_evil: 

Good news is that we've deprecated the last option:
https://github.com/dart-lang/pub/blob/master/doc/repository-spec-v2.md#deprecated-inspect-a-specific-version-of-a-package
(though we still have to support existing clients, the fix is not in Dart `2.7.1`)

Am I missing something?
