### ISSUE TITLE
Versions tab on pub.dev does not seem to work

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub-dev#3439]
When I click the versions tab, nothing happens. 
I tried on various packages. For example https://pub.dev/packages/msgpack2

**Comment by isoos** [comment]
@zoechi: could you please share more details about your setup? OS, browser, plugins...
Is there a console message in your browser that indicates an error?

**Comment by zoechi** [comment]
Firefox 86.5 Linux
Chromium 80.0.3987.132
No console output
Same behavior in both.
The only installed plugin is Bitwarden.

What I found is that in source view there is 
```html
<a href="/packages/msgpack2/versions" data-ga-click-event="tab:versions">Versions</a>
```

and when I click on that link it switches to the versions tab.

It's weird that this navigation does not happen when I click in the rendered view.

When I mouse-over I see the light-grey horizontal bar from the tab component like like with the other tabs.

The caption text `Versions` becomes a tiny bit lighter on mouse-over, which is not the case with the other inactive tabs. 
It looks a bit like the tab might be disabled.

**Comment by isoos** [comment]
@zoechi: thanks for the details. Could you please also take a look on the Network tab if/what kind of requests were blocked?

**Comment by zoechi** [comment]
www.googletagmanager.com and adservice.google.com are failing (because of my DNS setting)

**Comment by isoos** [comment]
I have a theory of what's happening:
- Normal browser without plugins and DNS blocking works.
- Use with ad-blocker plugins works, because they both block googletagmanager.com and our `gtag.js` script.
- @zoechi's setup of DNS blocking is broken because googletagmanager.com is blocked, but out `gtag.js` is running, and the onclick event does not receive the callback here:
  https://github.com/dart-lang/pub-dev/blob/master/static/js/gtag.js#L21

Possible solutions:
- detect if gtag is loaded and block the click event (for the beacon) only if it is loaded
- setup a timer (400ms) and update window.location regardless of gtag and beacon event

**Comment by zoechi** [comment]
Should this be live already?
I can still reproduce.

**Comment by isoos** [comment]
@zoechi: this will be deployed later.

**Comment by zoechi** [comment]
Ok, it's working now. Thanks!
