### ISSUE TITLE
Migrate away from package:uuid

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pub-dev#3440]
The readme says:

> Defaults to non-crypto generator, see UuidUtil for cryptoRNG

See: https://pub.dev/packages/uuid

I suggest we don't use it, it's just too risky -- let's move to `ulid` whenever possible. And when doing so verify if we rely on randomness. I was looking at using `package:uuid` for locking, but don't trust it.

**Comment by kevmoo** [comment]
https://github.com/dart-lang/pub/blob/8f21b1f56dd879c85f05df1125ec9bbe7c82cc9e/lib/src/utils.dart#L524-L545

There are even tests!

https://github.com/dart-lang/pub/blob/429a06039d185149f387a65e3503b0693ce6d24e/test/utils_test.dart#L106-L126

**Comment by isoos** [comment]
Our atom feed uses a v5 (namespace + seed) UUID to preserve a consistent ID for the feed readers. I think instead of that we could use the SHA hash (of the `'$package/$version'`) as the ID going forward.

The rest of our uses are just "random strings". I don't particularly care about the version-identifier bits properly set for a random UUID, so `ulid` or any random string would be fine.
