### ISSUE TITLE
Investigate memory usage of front-end

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/pub-dev#3450]

**Comment by isoos** [comment]
I've done a load test with a local instance connecting to staging. After ~2 hours and 12k+ requests served (random API calls, package pages and searches), I haven't observed an increase in the memory consumption of the VM.

Maybe we should try to close and re-connect the RPC connections (to redis, search service and Datastore)?

**Comment by isoos** [comment]
I've done further investigation into memory use, focusing on `StringInternPool`, which is used both in `search` service and in the frontend's dependency tracker isolate. In both cases I've simulated the long-term use by running the initialization phase multiple times (5-10x), and measured the difference in both currently used and maximum heap memory.

- `search` used it with a limit on how many items are in the pool. There was little to no benefit of using the `StringInternPool`, maybe 1-3 MB difference while the app+index overall took ~900MB.

- Dependency tracker used it without a limit on the maximum numbers, however, it only stored the name of the packages (+ a variant of that). Using the intern pool showed benefits (~40 MB), but to my surprise, rewriting small bits in the tracker (and replacing `StringInternPool`) reduced further 25 MB to the memory used.

Because of the above, I'm going to remove the `StringInternPool`, and use the updated code for dependency tracker.

I have seen no signs of further memory buildup with or without the interning when I've switched from 5 updates to 10.
