### ISSUE TITLE
[Feature Request] Add upload date info to public API

### ISSUE THREAD

**Issue by mateusfccp** [dart-lang/pub-dev#3565]
I am making something similar to #2339, but it's a CLI instead of a plugin. One of the functionalities will be to state what is the latest version and when it has been released.

I have the option to scrap the page `https://pub.dev/packages/{package}/versions`, but I think it would be nice to have this info on the API instead.

**Comment by isoos** [comment]
@mateusfccp: I think this is a reasonable information to be exposed on the API (/cc @jonasfj for a second opinion). I'm curious: what kind of tool are you building?

**Comment by mateusfccp** [comment]
Well, here where I work my Software Analyst proposed us to don't upgrade versions whenever we want, and said it would be nice to have a tool that could compare versions so we can see what is the current version of the packages and when it has been released.

The output will be something like:
```
+--------------+--------------+-----------------------+-----------------------+
| Package Name | Version Req. | Resolved.             | Last Version.         |
+--------------+--------------+-----------------------+-----------------------+
| rxdart       | ˆ0.23.0      | 0.23.1 (2019-12-13)   | 0.24.0 (2020-04-14)   |
| <package 2>  | <versionreq> | <version (rel. date)> | <version (rel. date)> |
| <package 3>  | <versionreq> | <version (rel. date)> | <version (rel. date)> |
+--------------+--------------+-----------------------+-----------------------+
```

**Comment by jonasfj** [comment]
The stable API is in: https://github.com/dart-lang/pub/blob/master/doc/repository-spec-v2.md

The stable API does not extend beyond that, if you use anything else I strongly advice that you handle the case when such API starts returning different responses.

Published time for the latest version can be reached from: https://pub.dartlang.org/api/packages/retry/metrics

But I emphasize that this is not stable.

@isoos, I agree we could add this information the stable API, I see only two concerns:
1. We should expose it with the same format as `new Date().toJSON()` in javascript (include the same number of decimals).
2. We should document this in [our spec](https://github.com/dart-lang/pub/blob/master/doc/repository-spec-v2.md) and find a way to do so, while indicating that the property is optional, hence, ensuring that clients never assume it always be present (otherwise, we risk breaking older pub servers).

@sigurdm, may be when `pub get` shows information like `newer version available` it would be cute to include a temporal hint. Like `newer version published 5 days ago`. 


------------------

@mateusfccp, I suggest you wait a few days, Dart 2.8 is shipping any moment now, and it'll feature a `pub outdated` command that will do most of what you're looking for. It'll also tell you the latest version of the package that will resolve with the other dependencies you have, in the scenario where you remove all version constraints (this is interesting if upgrading to new major versions).
