### ISSUE TITLE
Please fix the search algorithm for packages

### ISSUE THREAD

**Issue by talamaska** [dart-lang/pub-dev#3574]
Whenever I search something on pub.dev I'm presented with too much irrelevant results
for example I search for "camera"
I'm seeing this 
https://pub.dev/packages/koukicons
https://pub.dev/packages/flame
https://pub.dev/packages/permission_handler_platform_interface
https://pub.dev/packages/flutter_beautiful_popup
https://pub.dev/packages/intent
https://pub.dev/packages/font_awesome_flutter

![image](https://user-images.githubusercontent.com/299973/80403446-432bc480-88c8-11ea-8d6f-07618f95af1d.png)

What are those api results?
I checked the package there is no camera in there. just icons

Sure they are on 3rd and 4th pages mostly but still.
In other cases its even more obvious
searching for "printing"
There is only one relevant result for POS printer
dart:core
dart:html
dart:async
gql
english_words
distinct_value_connectable_stream
dart_mssql

check cordova plugins search page
https://cordova.apache.org/plugins/?q=printing
everything is related to printing.

I understand that in dart print and debugPrint, are used for showing text in the console and debug data, but that's a different story

Maybe when publishing a plugin, the authors should point a meaningful description and maybe some keywords for an existing list.

You get my idea.

**Comment by isoos** [comment]
@talamaska: thanks for reporting this, we always thrive to provide a better search.

For the `camera` search, you'll get the package results, because:
- `package:koukicons` has a library called `camera.dart` and has a `KoukiconsCamera` class
- `package:flame` has `BaseClass.camera` which has a documentation text "Camera position; every non-HUD component is translated so that the camera position is the top-left corner of the screen."
- `package:permission_handler_platform_interface` has `Permission.camera` which has a documentation of "Android: Camera iOS: Photos (Camera Roll and Camera)"
- `package:flutter_beautiful_popup` has `TemplateCamera` class
- `package:intent` has `CAMERA_FACING` field
- `package:font_awesome_flutter` has `FontAwesomeIcons.camera` as icon data

As you can see, these results were presented, because the packages public API contained the query string `camera`. As you can see, camera can be present and mean different things in different context. I'm not sure how we could filter out such results, open for suggestions.

For the `printing`, I see similar matches:
- `dart:core` has `print` function
- `dart:async` has zones which allow override of said `print` function
- `dart:html` has `Window.print`
- `package:gql` has `printNode` with documentation "Prints any AST node as String" 

`printing` is even more generic compared to camera, which can mean even more things based on the context.

> Maybe when publishing a plugin, the authors should point a meaningful description and maybe some keywords for an existing list.

We already use that, and if present, it is considered a higher-weighted signal than e.g. the API results you are seeing there.

Again, we are open for suggestions, but we'd prefer to keep API search around, as it provides value to surface results from the actual code too.

**Comment by talamaska** [comment]
Well, I'm sure that everybody who searches for camera doesn't mean searching for icons and Flame's camera is completely different from the phone camera. I mean choose tags from a predefined list, like native plugin or anything requiring platform channel, icons - many, UI element for any kind of ui widgets, communication (for bluetooth , wifi, websocket, http, dio, etc), state for redux, mobx etc, dependency injection for get-it, kiwi, inject.dart, tools - for animation packs, date utils, and such

**Comment by isoos** [comment]
With #3623 merged, we'll decrease the weight of the API results (both symbols and documentation). This will take effect in the next pub.dev release (probably within a week or two), and it should promote packages with phrases more relevant to search better. As we have no immediate plans to change anything else with the ranking and search, I'm closing this issue.
