### ISSUE TITLE
Health Scoring should not be deducting score based on dartfmt

### ISSUE THREAD

**Issue by KOGI** [dart-lang/pub-dev#3624]
URL: https://pub.dev/packages/etcd#-analysis-tab-

Since this is my own project, I should have the option to decide whether or not I will follow the dartfmt standards. These checks are only in place for the main package in question (not its dependencies), so if anyone else were to depend on my package, my intentionally different formatting already won't affect them.

At the very least, this check could be enabled by default, and there could be a way for a publisher/author to intentionally disable the check.

**Comment by sigurdm** [comment]
We score based on formatting, because projects that are formatted are easier to contribute to.

Using a default formatter doesn't make everyone(anyone?) happy, but at least it's super easy, and it saves a lot of time otherwise spent discussing formatting issues.

See more about the philosophy here: https://github.com/dart-lang/dart_style/wiki/FAQ .

We do allow non-formatted/differently formatted code on pub - we just rank it lower.
