### ISSUE TITLE
Health analysis is not honoring analysis_options.yaml

### ISSUE THREAD

**Issue by KOGI** [dart-lang/pub-dev#3628]
URL: https://pub.dev/packages/nats_dart#-analysis-tab-

Nearly all of the linter suggestions being reported on my project above are lints that I have consciously  disabled in `analysis_options.yaml`, but the health analysis is still deducting a significant number of points for their presence.

Health analysis should honor the settings in `analysis_options.yaml` to avoid unexpected score deductions.

**Comment by isoos** [comment]
@KOGI: The override is by design: pub.dev wants to encourage packages to follow the same best practices and coding standards, making it easier for others to read the published code and contribute to it when needed. This goal can be done only if we override the `analysis_options.yaml` provided by the package.

There is always room to contest some of the rules (e.g. in `package:pedantic`), and we are planning to update the scoring model to be more lenient on certain style rules. I'm curious though: why did you disable e.g. `unawaited_futures` or `unnecessary_new`? The former is really great to catch async bugs, while using `new` is... no longer necessary.

**Comment by KOGI** [comment]
It's a very common case that I want to kick off a future async in the background without waiting for it, and I find hints about them too frequent to the point of being distracting. Although, I must admit, I pulled that config from another project of mine and it may not be entirely appropriate in this project -- I will review that one.

As for `unnescessary_new`, I find that a significant portion of the time, retaining the `new` keyword helps with readability in longer/chained lines to make it more obvious that we're instantiating a new object rather than just calling a function. Personal preference to be certain, but as the author shouldn't that choice be left to me?

It would be really nice if there were a way that Pub could define options like `some_directive: required_true` vs `some_directive: recommended_true` -- though, that would require dynamically merging/generating a template with the project's settings to get a resultant ruleset before analyzing the package.

**Comment by jonasfj** [comment]
We are reworking the scoring model.. but `pub.dev` probably won't be without opinions.

However, not targeting a perfect score is perhaps reasonable in some cases.
