### ISSUE TITLE
How to contribute & run locally

### ISSUE THREAD

**Issue by chimon2000** [dart-lang/pub-dev#3645]
I would like to contribute to this project, but it looks like that is not possible without being able to create a Google Cloud key for the **dartlang-pub-dev** project.

**Comment by isoos** [comment]
@chimon2000: I'm curious: what kind of contributions are you looking forward to do?

The [development](https://github.com/dart-lang/pub-dev/blob/master/doc/development.md) page may be a bit out of date of what is possible.

While the "simple" track of running the project requires access to a Google Cloud project, it may be your own private project as well, it does not need to be `dartlang-pub-dev` per se.

We also have a [gcloud-emulation package](https://github.com/dart-lang/pub-dev/tree/master/pkg/fake_gcloud), which can be used to run the project entirely on localhost (in-memory), and the [integration tests](https://github.com/dart-lang/pub-dev/tree/master/pkg/pub_integration) use that. The missing piece with that is the seeding of the local database.

We have a not-yet-complete project for that, where one can specify a [test profile](https://github.com/dart-lang/pub-dev/tree/master/app/lib/tool/test_profile), and it will be able to fetch all the packages and their dependencies from pub.dev and build a site locally (or in a Google Cloud project).

Let me know if these pointers help you, and feel free to ask questions.

**Comment by chimon2000** [comment]
I'd love to contribute in any way that I can. Specifically, I wanted to try and tackle #3203, but ran into issues trying to setup my local environment.

**Comment by isoos** [comment]
For the liked packages page, we are planning to implement #3627 (sort by date instead of alphabetical) soon, as it is a small change overall.

However, #3203 will be a lot more complex, as it requires multiple pieces of data, which are to be request from Datastore in separate queries, and they will take a long time for a user with lots of liked packages. To be efficient, we'll need a rollup entity that has all the required data pre-calculated (which is a bit complex in the context of score, as score calculation depends on the runtime, and we would like to be able to roll back a version without rolling back the entire database). 

For the first contribution, I'd probably look for an easier to fix issue.

**Comment by chimon2000** [comment]
Can do. What label do you use to identify good issues for first time contributors?

**Comment by isoos** [comment]
@chimon2000: FYI: #3648 is a PR for #3627.

As for simpler starter issues, maybe #2181 or #1562 would come close. /cc @jonasfj for future tagging.

**Comment by chimon2000** [comment]
Awesome! Is there work to make it so the project can be ran locally?

**Comment by jonasfj** [comment]
Technically, running it locally is possible... Just create a GCP project and use that instead of `dartlang-pub-dev` (arguably one would need to fix the places where we've hardcoded it).

@isoos, maybe we can find some contribution opportunities for improving the ability to run it locally? Maybe we can fake all the cloud services such that local development doesn't need a GCP project.

Long term, we probably want the ability to develop using different GCP projects, and run tests ideally without a GCP project at all.

**Comment by isoos** [comment]
We've implemented a [fake_server.dart](https://github.com/dart-lang/pub-dev/blob/master/app/bin/fake_server.dart) that will run most of the pub site locally, with an in-memory fake datastore and storage.
