### ISSUE TITLE
Links in README should open in a new tab

### ISSUE THREAD

**Issue by tusharojha** [dart-lang/pub-dev#3653]
Hi there,
I have a suggestion for website improvement i.e. while browsing different packages containing links to their sample apps, documentation, etc. the website opens them on the same page which is annoying. If it opens in a new tab by default then it will help people browsing multiple links from the package's readme.

**Comment by isoos** [comment]
@tusharojha: Thanks for reporting this. I can conform that while opening them via right click + open in new tab works, using CTRL/CMD+click does not work the same way.

@jonasfj: It seems to me that this is caused by the analytics we are using on the tabs. I think this analytics can be removed, as the regular page load events would be enough for us. wdyt?

**Comment by tusharojha** [comment]
using CMD + click opens the page in a new tab but focuses on the current tab maybe because of browser features/settings.

**Comment by jonasfj** [comment]
@isoos, if analytics is causing regressions then rip it out, and file an issue to fix it. In this case we're changing away from tabs on the same page to using different pages. So maybe we just get rid of the event altogether.

> using CTRL/CMD+click does not work the same way.

I can't reproduce. I tried both with and without content filtering.

**Comment by isoos** [comment]
@jonasfj: My bad, I was focusing on the detail page's tabs, which - in the new design - should be able to open with CTRL+click, but they are not doing that. I'll fix the analytics collection for that.

@tusharojha: We do have a few places, where we open links in new window/tabs, but these are limited in their number and scope. One example for such place is the consent page, where you can accept to be an administrator for a package, and linking to the package page opens in a new window/tab. We do that only when we are sure that the user don't want to lose the current tab's state. We cannot be sure about that in the generic case, especially if the user is on mobile.

As CTRL+click opens these links in new tabs, and it can be easily accessed on mobile too, I think it is safer to keep most links on the standard behaviour.

**Comment by tusharojha** [comment]
@isoos: As I said before, it is just a suggestion and something which I feel good to have but I also agree with your opinion and let it be the same for now.
Therefore, I am closing this issue now.
Thanks

**Comment by jonasfj** [comment]
I think it makes sense to be reasonable careful about `target="_blank"`.

I often associate over usage of `target="_blank"` with sites that prefers to annoy me, rather than having me leave the site (I don't like such sites, hehe)..

Of course there are cases where it makes a lot of sense, for example, opening help while in the middle of some task.
