### ISSUE TITLE
Library got unindentified 

### ISSUE THREAD

**Issue by jhomlala** [dart-lang/pub-dev#3709]
There're issues with pub dev running new pana. Check my library: https://pub.dev/packages/catcher
* Library got unidentified card
* Library got No valid SDK error

This happens when pubdev started using pana 0.13.9+1. Previous pana 0.13.8 was working fine. What's the issue here? If you could point what's wrong with library configuration, then I'll be happy to fix it.

Here is configuration for Catcher: https://github.com/jhomlala/catcher/blob/master/pubspec.yaml

Thanks,
Jakub

**Comment by sigurdm** [comment]
catcher only has
`plugin: platform ` declaration for web. That makes pana think it is only compatible with web.

But the dependency package:package_info/package_info.dart is not supported on web (we only manage to detect that in 0.13.9+1).

So pana concludes that no platforms are supported.

You should make a (dummy) platform declaration for each platform.

That would make your package get android and ios supported.
But because pana only analyses the "root" library (named as the package) that would not give you the web tag.

One solution is to use conditional imports, and only import the web part when on web, and the io part on other platforms. Not sure how well that would work for your case. Pana knows how to handle conditional imports (when they are conditioned on libraries depending on the platform).
```
import "something.dart" if (dart.library.io) "other.dart"
```

We should perhaps consider how we handle root libraries again.
cc @jonasfj

**Comment by jhomlala** [comment]
Thanks. There were 2 problems:
* root class was named catcher_plugin instead of catcher (pana searched for class named catcher.dart and he couldn't find it)
* There were no dummy platform declarations

Now it doesn't show error but few warnings.

**Comment by isoos** [comment]
This has been fixed.
