### ISSUE TITLE
Filter search with executables

### ISSUE THREAD

**Issue by mnordine** [dart-lang/pub-dev#3780]
I want to be able to restrict my search to packages that have executables: https://dart.dev/tools/pub/pubspec#executables

**Comment by isoos** [comment]
@mnordine Thanks for the suggestion!

@jonasfj: Could this be a `has:executable` tag?

**Comment by jonasfj** [comment]
If the `executables` setion is present, then `is:tool` or `is:executable` might be better.

IMO, we should determine these tags in `pana`.

Note. having files in `bin/` is also a thing... because then you can call it with `pub run <packageName>:<filename>`  or `pub run <packageName>` in the case of `bin/<packageName>.dart`.

Hence, when `executable` section in `pubspec.yaml` is used, it's because it's supposed to be used with `pub global activate <package>`.

**Comment by isoos** [comment]
I believe the relationship is the following: all `executable` entry must point to an existing file, but not every file in `bin/` needs to have a matching `executable` in `pubspec.yaml`. (This itself is something to verify in `pana`.)

I agree, we should probably focus on the files in `bin/` instead of relying only on the `pubspec.yaml`. But for me `has:executable` could cover both (or rather the files in `bin/` - having an entry in `pubspec.yaml` is only an additional property of them). The package itself is not executable, but is has executable files...

**Comment by sigurdm** [comment]
We should maybe have a top-level key in the pubspec.yaml, indicating that a package is a "tool" and should be analyzed in the context of running in the dev-environment, not in the target platform. (eg. mirrors might be allowed even though you use flutter).

**Comment by mnordine** [comment]
Was just looking for this again on pub today.

**Comment by isoos** [comment]
Note: we have deployed a `pana` version that grants `has:executable` tag for packages that have dart files in their `bin/` directory. Analysis and search updates are ongoing, they will complete in the next day or so.

There won't be a separate UI checkbox for this, and so far we haven't decided how otherwise this will be exposed, other than typing it into search. We are open for suggestions that do not clutter the advanced section of search (please open a new issue for that, as I'm closing this for now).

**Comment by sigurdm** [comment]
We could document it in https://pub.dev/help/search
