### ISSUE TITLE
display the SDK if the pubspec constraints cause breakage

### ISSUE THREAD

**Issue by liyuqian** [dart-lang/pub-dev#3854]
As suggested by @johnpryan. An example package with this issue is flutter_svg

**Comment by isoos** [comment]
For reference: the platform classification failed because the package requires a non-stable Flutter release. It is reported at the end of the report sections, but only in the last one, while the prior one failed with it too:
<img width="763" alt="Screenshot 2020-07-20 at 11 42 55" src="https://user-images.githubusercontent.com/4778111/87923649-1bd73480-ca7e-11ea-935c-e4168e8edefa.png">

**Comment by johnpryan** [comment]
It sounds like this is the expected behavior. I think since `flutter_svg` is using non-stable SDK it would need to publish this version as a [prerelease](https://dart.dev/tools/pub/publishing#publishing-prereleases) instead of a stable version.

**Comment by johnpryan** [comment]
I guess that begs the question, do these checks run on prerelease versions?

**Comment by isoos** [comment]
> I think since flutter_svg is using non-stable SDK it would need to publish this version as a prerelease instead of a stable version.

+1

> I guess that begs the question, do these checks run on prerelease versions?

Yes, the same checks run on all versions (and you can see it on the separate versions pages), however, only the latest stable version's score is used in search for ranking.

**Comment by isoos** [comment]
We've started to display the minimal Dart SDK constraint on the version page, and started to use two SDKs for analysis: beta SDKs when the constraint requires it, stable SDK otherwise. I think these cover most part of this issue, please file new issue if you experience something that doesn't seem to be right.
