### ISSUE TITLE
Do not require "Support multiple platforms'" for code-generators

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/pub-dev#3862]
Currently, all code-generators see their score deduced of 10 points, as they only work on one platform.
But that is their expected behavior.

Maybe the dependency on `package:build_runner` could be detected, such that the requirement is skipped.

**Comment by isoos** [comment]
Thank you for bringing this up: this is a topic that requires careful balancing, and we are open to new ideas. At the same time, we need to consider multiple aspects of this problem, I'll try to collect a few here:

Granting more pub points for packages the support multiple platform is a tough choice: we want to promote multi-platform packages, at the same time we are aware that package with narrow scope (e.g. build-only, JS-only, Android-only, dart:ffi-based interop-only) will get fewer points. However, this allows a uniform, easy-to-understand score, which can be applied to all packages. Presumably, packages with similar constraints will get similar scores (as they are not able to support the other platforms the same way), and their relative rank in the package listing is unaffected by the uniform scoring rules.

The alternative would be to introduce different categories (there would be many more than the 4 listed here), each of them granted points with different rules. While the technical means to have separate categories with separate score ranges is available, the scoring system is not only for the package author, it is for the potential user of the package too. Besides the difficulties to communicate why a specific package gets that category and score (or multiple categories with multiple scores, why the overlap, etc.), the problem is with the difference of the score itself.
When browsing and searching for a package, we'd need to display scores that are comparable and meaningful in a consistent way. E.g. mixing an Android-specific score with a build-system-specific score on the same result page would be very confusing and would not provide much value.

On the plus side of the single score, we do have a mechanism to differentiate the ranking for specific use cases: if the search scope is specific (to an SDK now, maybe to a runtime/platform later), we do have specificity-ranking. E.g. if you select the Dart SDK as a filter, packages that support only the Dart SDK will rank higher compared to the ones that support both Dart and Flutter.

**Comment by isoos** [comment]
Please continue the discussion on the other issue.
https://github.com/dart-lang/pana/issues/720#issuecomment-667926015
