### ISSUE TITLE
Pre-release SDK constraints should not require a pre-release version

### ISSUE THREAD

**Issue by grouma** [dart-lang/pub-dev#3897]
The following error should only be a warning:

`Packages with an SDK constraint on a pre-release of the Dart SDK should themselves be published as a pre-release version. `

See this specific example: https://github.com/dart-lang/build/pull/2753

**Comment by athomas** [comment]
@sigurdm and @jonasfj are OOO.

Given that these issues seem connected to the stable release that is slated to go out on Monday, I have asked @isoos and @sortie to prepare for deploying a revert.

**Comment by leafpetersen** [comment]
Thanks @athomas !  @jakemac53 are you unblocked from landing these fixes now?

**Comment by sortie** [comment]
I am currently deploying them to production. It should be fully up in about an hour.

**Comment by sortie** [comment]
The traffic has been switched on pub.

**Comment by sigurdm** [comment]
I guess this means we have to implement the warning in the client?

**Comment by isoos** [comment]
> I guess this means we have to implement the warning in the client?

We could also keep the rule and have a case-by-case opt out.

**Comment by mit-mit** [comment]
I browsed though this thread, and the linked bugs, but I still don't understand why we need a change. 

I still believe this needs to be *an error*: A package which depends on a pre-release package *is* itself pre-release and this should be versioned as such.

What is the canonical use case where this is intractable?

**Comment by mit-mit** [comment]
> Consider also the following scenario for any package depended on by flutter:

> 1. The SDK releases some new feature that a package wants to use.

This is in a non-stable SDK, right?

> 2. The package starts using it, and has to stay at a pre-release version.

Yes, it definitely should. It's using a feature which has no stability promise and could be removed at any point in time.

> 3. We start preparing the stable flutter/dart sdks, and want to update to the latest version of said package in flutter.

> We cannot publish a stable version of the package because it depends on a dev SDK, and the stable SDK is not yet released

Yup, sounds correct.

> At the same time flutter stable should really not be pinning dev releases of packages (null safety being the exception right now, but not likely a strategy we want to repeat)
> How do we resolve this scenario? Do you have to wait two stable releases before using any new sdk feature in a package depended on by flutter?

Why can't we publish the stable version of the package that depends on the about-to-be-stable SDK? It would not be resolvable until the stable SDK ships, but that's the behavoir we want, isn't it?

**Comment by jakemac53** [comment]
Regardless about how you feel about depending on features that only exist in a dev SDK, there are other reasons that you may need to depend on a dev SDK in a stable release which we can't predict.

This is exactly what happened here - we needed people to get a different version of `build_runner` depending on their language version (ie: major/minor sdk version), otherwise _they would be broken_ (and were actively broken). This needed to be a stable release of build_runner because otherwise most people would not get it (they would instead get some older version). We had to choose between breaking our flutter stable users or our flutter master/dev/beta users, and ended up choosing to break the non-stable users until we could publish a version for them.

In the original design document where we agreed _not_ to make this an error, I called out another possible scenario where the SDK could make a breaking change (this happens relatively often). You might need to release a version of your package with a backwards incompatible fix, so it would need to set the min version to a dev version of the SDK, but you would need all users on that sdk to pick it up, so a stable version release is the correct solution to fix users on the dev channel.

We can't possibly understand ahead of time all the reasons people might have for needing to have a dev constraint on the SDK. The bar for blocking publishing of packages without any workaround needs to be a lot higher than a concern about features being reverted, especially when it actually blocks us from fixing real world, concrete breakage.

> Yes, it definitely should. It's using a feature which has no stability promise and could be removed at any point in time.

I disagree with this assessment. Any breakage that could occur would happen during the pre-release window, and will only break users who have already opted into some level of breakage by being on the pre-release sdk.

There is a lot of value in having these users pick up versions of packages that _actually use_ the features provided by their pre-release sdk. Isn't this in fact the primary reason for having a pre-release sdk channel at all?

> Why can't we publish the stable version of the package that depends on the about-to-be-stable SDK? It would not be resolvable until the stable SDK ships, but that's the behavoir we want, isn't it?

This would break flutter and put it in a state where it can't be tested because its dependencies aren't valid.  Beyond that, this is a strictly worse solution than  allowing us to publish versions that depend on a pre-release. You are effectively doing exactly the same thing, except you can't even run your code to validate it works.

See also my concern re: NNBD releases. We want users to pick up these packages _before_ the stable null safety release, during the stabilization period. This will lead to a much better experience for users since the second many of them will already have the null safe dependencies the first time they run on the new sdk (whether they use `pub get` or `pub upgrade`).

**Comment by jonasfj** [comment]
> This would break flutter and put it in a state where it can't be tested because its dependencies aren't valid.

We could publish the same code as pre-release and stable release, only bumping the version number.
But we don't have tooling to do this automatically, nor is it impossible that simply changing the version number can break a package (it shouldn't but people do embed these in code and sometimes tests -- mostly seen in pana).

**Comment by jakemac53** [comment]
> We could publish the same code as pre-release and stable release, only bumping the version number.

Flutter pins a single version for all its deps so we can't put a version range that allows both 🤷‍♂️ 

I would also like to re-iterate that publishing a version of a package which claims support for a _non-existent_ sdk is strictly less safe than just allowing publishing of stable versions that require some pre-release sdk version. At least with the latter you can validate the code and not have broken travis jobs etc.

**Comment by natebosch** [comment]
> Yes, it definitely should. It's using a feature which has no stability promise and could be removed at any point in time.

In this particular case the "feature" was "the language version becomes `2.10`" which, if removed from the stable SDK release, would be an enormous problem.

There are many reasons we publish packages with more recent SDKs. Sometimes it's a bug fix, sometimes like above it's about fixing versioning issues unrelated to specific SDK features.

I feel strongly that this is an area where most authors want to do the right thing and we only need to help them from making easy mistakes.

> It would not be resolvable until the stable SDK ships, but that's the behavoir we want, isn't it?

No, generally if we wanted that behavior we'd publish when the SDK ships. When we publish with a pre-release constraint it is generally because we want folks to pick it up, or because the folks already on that SDK _need_ to pick it up.

I worry that the unusual patterns of null safety around SDK and package releases has made us lose sight of the years of experience we have doing this already... This is something that we know is both necessary and safe, because we _have_ needed to do this and we _have_ done it safely.

**Comment by jonasfj** [comment]
> I would also like to re-iterate that publishing a version of a package which claims support for a non-existent sdk is strictly less safe than just allowing publishing of stable versions that require some pre-release sdk version.

Yes, there are plenty of other pitfalls.. You can also publish a stable version that depends on a prerelease of some other package, and thus, use transitive dependencies to achieve a stable version that requires a prerelease SDK.

**Comment by jonasfj** [comment]
Closed as resolved, we're going to only keep this a warning.

**Comment by gmpassos** [comment]
Definitely a package that depends on a pre-release should be blocked, unless published as a pre-release, since the main idea to publish something is for the public, and the public won't be able to use the package normally.
