### ISSUE TITLE
Type of Google account for enterprises

### ISSUE THREAD

**Issue by NicolasToussaint** [dart-lang/pub-dev#3928]
We are an enterprise and wish to create a Google account (and then Verified Publisher) in order to publish new packages on https://dart.dev/

However, there are [4 types of google accounts](https://support.google.com/work/android/answer/6371476), and it is unclear which one is required... One is one personal accounts, and the others for enterprises but none seem to fits precisely for what we need.

Does any of you have been confronted to the same problem, or could share experiences ?

Thanks

**Comment by guidezpl** [comment]
Anecdotally, I made a verified publisher with my personal account

**Comment by jonasfj** [comment]
There is no account requirement from `pub.dev`.

The kind of Google account you use typically depend on you situation. For large organizations _suite accounts_ often makes sense, because you can manage the accounts, things like restore access or disable accounts after an employee leaves.

---------------
In general, I think the most important thing is to follow recommendations to have 2-factor-authentication protecting your Google account:
https://www.google.com/landing/2step/

**Comment by NicolasToussaint** [comment]
Thanks @jonasfj for the details
