### ISSUE TITLE
Fake package with copied code, and license violation.

### ISSUE THREAD

**Issue by jonataslaw** [dart-lang/pub-dev#3935]
Okay, I know that this is not the appropriate place to request package removal, however, after my law firm and I contacted pub.dev via email support@pub.dev, we didn't get a response to something that Is it urgent.
A scammer is posing as one of Flutter's most popular packages today, Getx. He copied the entire source code of version 1.11.0 of the package, took advantage of the fact that there was no package with the name "getx" (previously my package name was Get, and due to SEO it was changed to Getx 2 months ago ), and recently sent that package.
All labels are fakes, and used to give an air of credibility to the package, to pass itself off as the original.
Many people are downloading this package, it has 58% popularity and 7 likes.
It is not known what its purpose is, it is probably a package scam that will insert some malicious code in the future.
Getx is a verified publisher.
I am the creator of the package that has been in pub.dev for almost 1 year
I am the copyright holder of the Getx brand.
I am the owner of the domain Getx.site which the package was verified on.
Although the community has been alerted, there are dozens of videos on youtube talking about "getx", and novice users are downloading the package by mistake.

Its is original package:
https://pub.dev/packages/get
![Screen Capture_select-area_20200813115757](https://user-images.githubusercontent.com/35742643/90150979-98e38a00-dd5c-11ea-9378-eb0476985460.png)

its is fake package
https://pub.dev/packages/getx
![Screen Capture_select-area_20200813115908](https://user-images.githubusercontent.com/35742643/90151025-a7ca3c80-dd5c-11ea-8fea-8cb3dc4d552c.png)

Its is original package
![Screen Capture_select-area_20200813120016](https://user-images.githubusercontent.com/35742643/90151089-bdd7fd00-dd5c-11ea-80fc-db8f476c1a0d.png)

Its is a fake package
![Screen Capture_select-area_20200813115954](https://user-images.githubusercontent.com/35742643/90151133-c7616500-dd5c-11ea-8713-d5f36c89c553.png)

**Comment by kauemurakami** [comment]
Something must be done **urgently**.
The responsible is acting with bad intentions.
This can harm the real package in tangible and intagible ways.

**Comment by GuiHS01** [comment]
If pub.dev continues to allow this kind of behavior, we will have a messier community than npm itself, where there are multiple duplicate packages and little moderation.

Not to mention, the content legal ownership issue is being directly inflicted, which is still deliberate deceptive plagiarism so that new users are easily fooled.

It's clear that the bundle clone's intent is to outshine GetX's growth and quality!

It is now the duty of the pub.dev administration to punish the person directly responsible (probably the clone of the package was published with a fake account ...), making sure that it does not violate the terms and does not mislead any member of the community. Only then can we trust the quality of the packages published here!

We are waiting for a clear answer on this matter!

**Comment by mit-mit** [comment]
Dart product manager here: We received the support ticket for this earlier today, and will process it carefully. It's been less than half a business day since we received it, and legal matters take time. If the pub.dev policy was violated, we will act on it.

As legal discussions are not appropriate to discuss and handle here in our technical issue tracker, so I will be closing and locking this issue.

**Comment by mit-mit** [comment]
Resolution: https://pub.dev/packages/getx was removed by moderation
