### ISSUE TITLE
Is Pub_Server outdated and if so is there a current version that's open sourced. 

### ISSUE THREAD

**Issue by Ihuds577** [dart-lang/pub-dev#3972]
Hey Everyone, hopefully this isn't something covered in a separate issue but I was looking around and saw that the pub_server repo is archived and I couldn't find a current version that replaces it. Is the new pub server repo closed source or is there something I'm missing? Thanks in advance!

**Comment by isoos** [comment]
@Ihuds577: We've abandoned the `pub_server` package because its abstractions and code structure was an impediment on the development on pub-dev, and we wanted to clearly indicate that the package is no longer maintained. But that is only the `package:pub_server` (most of which was developed in 2015), and not the generic concept of the pub server, or the pub.dev site - we keep improving the later, and we are planning to support self-hosted pub in both the server and the client.

To give you an example of the changes there: the flow to invite an uploader changed from being automatic (you just did `pub uploader add X` and `X` was added to the package as uploader), to being confirmed by e-mail and then confirmed on the UI. The classes in `pub_server` were designed only with the first option in mind, and we needed the flexibility to extend that to support better security in pub.dev. If we wanted to have the code updated in `pub_server`, we'd release a breaking change with all of these updates, while in practice the API remained the same. Not a hard thing to do in itself, but things add up, while the users would be also forced to change their code...

The actual api required for the `pub` client is rather narrow, and should be easy to implement it:
https://github.com/dart-lang/pub/blob/master/doc/repository-spec-v2.md

You can also track the current pub.dev implementation of the APIs starting from this file. As you can see the current API surface of pub.dev is much larger than the API in the spec or in `pub_server`. At this point we do not want to commit supporting these endpoints long term, only the ones in the repository spec above.
https://github.com/dart-lang/pub-dev/blob/master/app/lib/frontend/handlers/pubapi.dart

Once we feel that the APIs become stable, we may release a new package with the API skeletons that could help to kick-start a new pub-server implementation.

Also, while the `package:pub_server` is archived, its code can be used to develop a custom pub server (it does follow the API spec after all). You can also check the https://pub.dev/packages/unpub package that is developed independently from pub-dev. We also in the process of developing a version of pub-dev that can be run locally, without appengine: https://github.com/dart-lang/pub-dev/tree/master/pkg/fake_pub_server

I hope the above sheds some light on what was happening there. I'm curious: what's your plan or use case wrt. running a pub server?
