### ISSUE TITLE
Guidance on how to solve score issues on cached_network_image

### ISSUE THREAD

**Issue by Zazo032** [dart-lang/pub-dev#4023]
`cached_network_image`'s pub.dev listing is showing 2 problems but there's no clear guidance on how to solve them:

### 10/20 points: Supports 2 of 3 possible platforms (iOS, Android, Web)

Pub reports the following issue:

<details>
<summary>Image</summary>

![image](https://user-images.githubusercontent.com/2807712/92714659-c53ef600-f35c-11ea-9d56-58cc38c66b21.png)

</details>

However, `web` platform is indeed supported and working (although without caching). Not sure about if it works on desktop platforms. In pub's listing, it doesn't even include `Android` and `iOS` as supported platforms, it just states `[UNIDENTIFIED]` (plugin only has Dart code).

### 0/30 points: code has no errors, warnings, lints, or formatting issues

Pub reports the following issue:

<details>
<summary>Image</summary>

![image](https://user-images.githubusercontent.com/2807712/92714720-d7b92f80-f35c-11ea-81c7-e2ea53da494f.png)

</details>

However, that function does indeed work, it may be a bug in the analyzer that I attempted to solve with `analysis_options.yaml`, but didn't work. Related to https://github.com/flutter/flutter/issues/52899.

---
Pub listing: https://pub.dev/packages/cached_network_image
Related issue: https://github.com/Baseflow/flutter_cached_network_image/issues/463

**Comment by jonasfj** [comment]
This seems like a problem on our end, because `path_provider` is a plugin and it declares Android support, so we shouldn't look at what it imports.

![6w7gRaFssyeSvjx](https://user-images.githubusercontent.com/149732/95184926-540e2980-07c8-11eb-8573-ac8bae891c67.png)

------

As for web support the problem seems to be that you're importing `package:sqflite/sqflite.dart` which doesn't work on web.

Solution to this is to only import `package:sqflite/sqflite.dart` conditionally.
See: https://dart.dev/guides/libraries/create-library-packages#conditionally-importing-and-exporting-library-files
