### ISSUE TITLE
Stop the Google login monopoly on pub.dev

### ISSUE THREAD

**Issue by frank06** [dart-lang/pub-dev#4106]
Google does NOT allow me to regain access to my account. I do have my username and password, but it's asking for a ridiculous security code that never works. I tried a million different things.

There is no human support, so when the system decides your out, **YOU'RE OUT**.

This is the gmail account I was using to publish the [Flutter Data](https://pub.dev/packages/flutter_data) package and others.

I put a lot of effort in developing these packages and now (because I traveled and attempted to log in from a different country) I lost all access to my pub.dev projects.

Please allow some alternative method, like Github login, or username/password.

@jonasfj

**Comment by jonasfj** [comment]
Supporting other forms of authentication, or at-least account linking is something we've considered.

But I don't think it's something we are going to prioritize. It's a lot of work, and it's not clear how account deletion would be propogated.
Accepting username/password directly would mean that we would have to deal with account recovery support, etc. I don't think we're considering that.

I'd be far more amendable to improving support for 3rd party pub servers in the pub client. It's mostly lacking because we haven't had time for it, but there is a contributor working on something so we'll see :)

---------


Support requests for pub.dev should go by email to support@pub.dev (drop us a line).

We generally can't do much to help with loss of Google account access, this is handled by other support channels. For good reasons: from the perspective of pub.dev I think it's annoying if you have to rename packages because you lost access, but it would be far worse if admins granted an attacker ownership of a package.

-------

In general the best advice I can give us to review your account settings, have 2 factor authentication enabled. Ensure that you have backup 2nd factor authentication too. Personally, I have multiple yubikeys associated with my account.

For more information see:
https://www.google.com/landing/2step/

**Comment by frank06** [comment]
@jonasfj Yeah, I understand it's a lot of work :) 

But do you understand my problem? I worked months on a project and now I can't update it anymore.

How can I recover access to pub.dev and push new versions of `flutter_data`?

**Comment by jonasfj** [comment]
I think I understand your problem, please direct it at support@pub.dev, like I said, I doubt there is much we can do -- but lets discuss individual support cases over email, and not in public -- please send an email explaining the situation to support@pub.dev.

----

In general I think google accounts are very secure, but if you didn't configure 2FA properly it can be really hard to prove who you are. And unfortunately, it doesn't help much to recommend using 2FA after you have problems authenticating.

**Comment by frank06** [comment]
I appreciate your help, Jonas.

If I did NOT enable 2FA it's for a reason.  I know I travel, I access my accounts from different places, and I don't have a single telephone number. Since when having a single telephone number is a requirement to do things on the Internet?

What on Earth is a password for?

Google accounts are horribly designed. It's the worst part of identity-based authentication.

**Comment by jonasfj** [comment]
Please drop a line to support@pub.dev to discuss your predicament.

-----

I'm no expert on Google accounts, but there are multiple options for 2FA.

**Comment by frank06** [comment]
I did send a message to support@pub.dev. Thanks!

Being an expert is not required. If someone didn't set 2FA, 2FA shouldn't be required in a new device. As simple as that.
