### ISSUE TITLE
Explicitly block robots from api.pub.dev

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dev#4177]
https://api.pub.dev/robots.txt should be

```
User-agent: *
Disallow: /
```

We're wasting bandwidth and search clarity with search engines hitting this – https://www.google.com/search?q=site:api.pub.dev

**Comment by kevmoo** [comment]
Should likely do it from https://www.google.com/search?q=site:www.dartdocs.org too!

**Comment by isoos** [comment]
Looks like we do allow api.pub.dev as production host, although we shouldn't serve the packages content on it:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/shared/configuration.dart#L144

https://www.dartdocs.org/robots.txt is a different issue, it seems that it is no longer forwarded to pub.dev, and it is a 404 instead of a rejecting `robots.txt`, which other domains should get:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/shared/handlers.dart#L132-L133

**Comment by kevmoo** [comment]
> Looks like we do allow api.pub.dev as production host, although we shouldn't serve the packages content on it:
> https://github.com/dart-lang/pub-dev/blob/master/app/lib/shared/configuration.dart#L144

What's it even for?

**Comment by isoos** [comment]
> https://www.dartdocs.org/robots.txt is a different issue, it seems that it is no longer forwarded to pub.dev, and it is a 404 instead of a rejecting robots.txt, which other domains should get:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/shared/handlers.dart#L132-L133

We actually do serve it from our frontend, and it is easy to fix that.

**Comment by jonasfj** [comment]
Yes, we should just return `404` from `api.pub.dev`, the aim was to use this for hosting all documentation. I think we still have a bug for that.

Let's just route all `api.pub.dev` requests to special handler that returns `404`, then in the future we can make that router return documentation.
