### ISSUE TITLE
The package english_words cannot be found via search

### ISSUE THREAD

**Issue by filiph** [dart-lang/pub-dev#4235]
URL: https://pub.dev/packages?q=english_words

The package is marked as unlisted, which is not something I remember doing myself. I do remember we talked about not showing `english_words` on the homepage. But even then, it would be good to show it when people search for it.

**Comment by isoos** [comment]
We no longer have the flag for removing a package from the homepage, only the `unlisted` flag which removes it from search entirely. I think you can remove the `unlisted` flag from `english_words`. At that time the homepage displayed the most popular packages with a fixed order, and since then we are using random sampling for displaying packages on the home page. `english_words` will be frequently displayed, but it will not dominate the page.

**Comment by isoos** [comment]
@filiph: As `english_words` is no longer the top package in usage or in the number of likes, I suggest to remove the `unlisted` flag, and see how it feels on the landing page and in searches. Let's see if it causes problems in search quality or otherwise...

**Comment by filiph** [comment]
Great! I un-unlisted english_words just now and it doesn't show up on the homepage, so I think we're good!
