### ISSUE TITLE
dev_dependencies dependencies should be isolated from source code dependencies

### ISSUE THREAD

**Issue by bitsydarel** [dart-lang/pub-dev#4611]
dev_dependencies dependencies should be isolated from the source code dependencies because their are not bundle with the app.

Because otherwise situation like that happens to often and it's really frustrating and limitating:

```shell
Because every version of flutter_driver from sdk depends on crypto 2.1.5 and analyzer >=1.0.0 depends on crypto ^3.0.0, flutter_driver from sdk is incompatible with analyzer >=1.0.0.
And because mockito >=5.0.0 depends on analyzer ^1.0.0, flutter_driver from sdk is incompatible with mockito >=5.0.0.
So, because teg depends on both mockito ^5.0.0 and flutter_driver any from sdk, version solving failed.
pub get failed (1; So, because teg depends on both mockito ^5.0.0 and flutter_driver any from sdk, version solving failed.)
```

Can't upgrade flutter dependencies and can't upgrade mockito dependencies.

**Comment by isoos** [comment]
@bitsydarel I do understand the frustration, having done similar upgrades in the past. However, we have dev dependencies for a good reason: we want to run the tests and/or the supporting infrastructure like code generators. You can't really run the tests if the versions they depend on are incompatible with the versions of the main app.

Having said that, for local development, you could also use dependency overrides, which could help while the migration of the dependent libraries stabilises:
https://dart.dev/tools/pub/dependencies#dependency-overrides

It is also helpful if you report the bad dependency constraints to the respective authors, as they may not be aware that they are blocking something, and otherwise could use a different constraint.
