### ISSUE TITLE
Nit: Navigating between the tabs shouldn't add browser history

### ISSUE THREAD

**Issue by jayoung-lee** [dart-lang/pub-dev#4637]
In the recent HaTS survey, at least 2 users commented that it's annoying that switching between the tabs adds browser history. 

The main drawback is that the users have to use the back button multiple times to go back to the last page they were on (such as the search result page).

**Comment by jonasfj** [comment]
hmm, I guess we made it separate pages because a page like: `/versions` can be a bit expensive to load.

Also we didn't like URLs like:
 * `https://pub.dev/packages/<package>#readme`
 * `https://pub.dev/packages/<package>#example`
 * `https://pub.dev/packages/<package>#changelog`
 * ...

Which also makes deep linking to specific sections on the readme / changelog harder to do.. for example:
 * `https://pub.dev/packages/retry#using-retryoptions`
 * `https://pub.dev/packages/retry/changelog#v300`

We could maybe do something with Javascript to switch tabs without reloading, or perhaps avoid history. But I'm not sure it wouldn't still be sensible to add browser history entries -- which I suspect we did before too. Usually, it's a history event to navigate to a `#label`.

-----------

If you think this is a concern please upvote this issue.

**Comment by jonasfj** [comment]
I see no upvotes for this. And others haven't complained since we changed from in-page tabs to multiple-page tabs.
