### ISSUE TITLE
Add size of package in the metadata section

### ISSUE THREAD

**Issue by JTPenn-EG** [dart-lang/pub-dev#4679]
Adding the size of the package to the metadata section will surely help developers into taking a decision whether the package is worth installing or not

**Comment by sigurdm** [comment]
You mean the size of the tar.gz archive, or how much space it will take in the final app?

**Comment by JTPenn-EG** [comment]
> You mean the size of the tar.gz archive, or how much space it will take in the final app?

If we can know how much space will it take then that would be wonderful, if there's no way to to know the exact space it will occupy in the final app, then hopefully the size of the archive would be as sufficient.

**Comment by isoos** [comment]
I think the size of the archive may be helpful if you are restricted on the network traffic, however, it may be a bad proxy for the final app for several reasons:
- the compression level may vary on different assets,
- the package may pull in many dependencies, and they could vary in size,
- the archive could contain assets for tests or otherwise unused in the final app.

We could probably scan the `bin/` and `lib/` directories in all of the package's resolved transitive dependencies (esp. if they are non-test dependencies), and sum the size of the files there. It may be useful to compare two competing packages that way.

**Comment by JTPenn-EG** [comment]
> I think the size of the archive may be helpful if you are restricted on the network traffic, however, it may be a bad proxy for the final app for several reasons:
> 
> * the compression level may vary on different assets,
> * the package may pull in many dependencies, and they could vary in size,
> * the archive could contain assets for tests or otherwise unused in the final app.
> 
> We could probably scan the `bin/` and `lib/` directories in all of the package's resolved transitive dependencies (esp. if they are non-test dependencies), and sum the size of the files there. It may be useful to compare two competing packages that way.

Exactly, It will also be very useful for flutter web apps as developers tend to minimize number of dependencies on web, so if someone finds a large package that does a simple task, he may do it himself.

**Comment by alphapokedex** [comment]
@JTPenn-EG It would be great to have this on pub as well, it helps out in making the APK as small as possible too without having to split it for each architecture. This repo has a similar feature for JavaScript ES6 packages. 

- [pastelsky/bundlephobia](https://github.com/pastelsky/bundlephobia)
- [bundlephobia.com](https://bundlephobia.com/)

**Comment by jonasfj** [comment]
I think it would be great to have more metrics, but talking about I think we're concluding that raw package size is not a good metric.

Because it is skewed by:
 * Treeshaking,
 * Test files included in the package,
 * Test data included in the package,
 * Image files included in the package -- some of these could simply be documentation.
 * API documentation comments...
 * Size and details of information in CHANGELOG and README

All of these things means that large packages are not necessarily bad. Indeed a package with lots of test is usually consider good :D

Even if we build the `example/` app that many package have, and measure its size... that's not a good metric. Because quality packages usually have heavy example apps that demonstrate very possible feature, thus, when you use the package a lot of those feature might not be included due to treeshaking.

----------------

Maybe other code complexity metrics could be added to pana.
