### ISSUE TITLE
Broken link to StreamQueue documentation

### ISSUE THREAD

**Issue by aidanstay** [dart-lang/pub-dev#4709]
URL: https://pub.dev/packages/async

<Describe your issue or suggestion here>
Broken link to the StreamQueue docs, clicking gives me a 404 not found.

**Comment by isoos** [comment]
@aidanstay: this issue tracker is for the pub site, and not for individual packages. Next time please report such issues to the package's issue tracker or to the authors.

However, in this case the bug was already reported and fixed, but not yet released: https://github.com/dart-lang/async/issues/156

**Comment by aidanstay** [comment]
Ty, sorry.
