### ISSUE TITLE
"search Flutter Favorite packages" doesn't filter to just Flutter Favorite packages

### ISSUE THREAD

**Issue by csells** [dart-lang/pub-dev#4895]
When I'm looking at [Flutter Favorite packages on pub.dev](https://pub.dev/flutter/favorites), the screen says "search Flutter Favorite packages" but the search results, e.g. bluetooth, show non-FF packages.

![image](https://user-images.githubusercontent.com/2568253/122810356-1c76dd00-d284-11eb-9eb6-42bb00d1e4d5.png)

I don't expect us to provide a search box that's filtered by just FF packages so I think it would be easiest to update the text input hint to not set the expectations then to implement filtering by FF packages.

**Comment by isoos** [comment]
Nice catch, thanks for reporting.

However, the actual search behavior is indeed searching within flutter favorite package, e.g.: https://pub.dev/flutter/favorites?q=prov

The bug is that we also use an exact-name match highlight, and SDK library results on the same result page, which is not something we should do in that context.

**Comment by csells** [comment]
@isoos when will this change roll out to pub.dev?

**Comment by isoos** [comment]
@csells: We don't have a release this week, maybe sometime next week.
