### ISSUE TITLE
Pub.dev is incredibly slow

### ISSUE THREAD

**Issue by waleedrana777** [dart-lang/pub-dev#4954]
URL: https://pub.dev/

<Describe your issue or suggestion here>

Whenever I search on or visit any link on Pub.dev, it takes 10-15 or more seconds to get the result which is extremely slow compared to modern standards and also that it is owned by Google. Such a large company and such slow website! Please fix it!

**Comment by isoos** [comment]
@waleedrana777: What were the expressions you were searching for? Could you please provide more detail about your setup: what's your OS, browser, (country, ISP, VPN) network setup, what extensions are you using? 

Asking these because I don't see any lag in search right now, so there is a slight chance that the issue might be somewhere else...

**Comment by waleedrana777** [comment]
I am using windows 10, edge browser, and I was searching for firestore cloud package! The issue is resolved. I don't know it is working pretty fast now!
