### ISSUE TITLE
Feature request: Allow a custom limit for the Atom feed

### ISSUE THREAD

**Issue by jcalado** [dart-lang/pub-dev#5161]
### Issue
Currently pub.dev's atom feed is limited to the 10 most recent packages:

https://github.com/dart-lang/pub-dev/blob/e7faba418b1969c8f73d6a60f29a5ddbd510b170/app/lib/frontend/handlers/atom_feed.dart#L25

This leads to an increased number of times a reader has to poll the server as to not miss new packages.
Sometimes 5 minutes is all it takes for it to already be missing packages.

### Proposal
What I propose is adding a URL parameter to set the limit instead of hardcoding it.

* Create an optional `limit` parameter
* Not providing the parameter would default back to `10`
* The value could have a safe upper ceiling, say 100
* Setting `?limit=200` in this case should drop back to the defined upper limit, 100

**Comment by isoos** [comment]
There seems to be an atom feed pagination API RFC, which I think most clients don't use, so we should not invest much time into it.  I don't see other package managers doing RSS feeds, maybe I'm missing something there. However, `blogspot.com` uses `?max-results=<number>` to allow non-default item counts, so maybe we should use that parameter name instead of `limit`.

My main worry is the current content: we serve the `README.md` of the package without trimming or any limit, which may become a problem, if we increase the item size. Instead, we should probably use only the package `description:` field from `pubspec.yaml` as the content. (That should be part of the cached `PackageView` object, and could be loaded from cache fast.) What do you think?

**Comment by HudsonAfonso** [comment]
now we have a feed that has only one line that doesn't explain what the package does or anything like that, it doesn't help at all...

README is important, CHANGELOG as well, now I have to develop something to retrieve this info, to keep myself up to date, probably with pooling

**Comment by isoos** [comment]
> now we have a feed that has only one line that doesn't explain what the package does or anything like that, it doesn't help at all...

Do you have a few examples where the package description (the single line that is in the feed) was not useful, while the readme was?

> to keep myself up to date

Curious: do you monitor and check every package being published?

**Comment by HudsonAfonso** [comment]
> Do you have a few examples where the package description (the single line that is in the feed) was not useful, while the readme was?
a package appears in the feed when it's new and when it's updated, when updated the description won't change, so it won't help at all, will just show up several times in the feed...
usually an updated package has new features and bug fixes, new features are usually in the README Usage block.
packages evolve and I use feed to follow this evolution and choose which packages best meet my needs

> Curious: do you monitor and check every package being published?
yes, most of them
packages die, unmaintained or change so that they no longer fit the project, I have to find alternatives
knowledge...

**Comment by isoos** [comment]
> packages die, unmaintained or change so that they no longer fit the project, I have to find alternatives

As most users won't keep up 100% with the RSS feed, I think this use-case is better served with search on pub.dev. We are open for suggestions how to improve this.
