### ISSUE TITLE
Search ranking looks broken

### ISSUE THREAD

**Issue by bsutton** [dart-lang/pub-dev#5375]
So I should say that I am starting from a point of self interest.

I have published a package on the pub.dev site called Money2.
It might be worth noting that I published a minor update to the package this morning.

Until recently if you search for the phrase Money it would come up as the 3rd of 4th package.

Today it's on page 3.

I've had a look at the published Ranking criteria and by all metrics it would appear that it should be highly ranked.
As a comparison point:

The Money2 package (Page 3) has:
* popularity: 94% 
* Score: 120 (now 130 but at the time of writing 120)
* Likes: 113
*  Readme with significant no. of references to the word Money

The Moneys package  (Page 1) has:
* popularity: 3%
* Points: 90
* LIkes: 5
*  Readme with significant no. of references to the word Money

The search results also contain Material and Cupertino neither of which seem to be useful results given the search criteria.

So whilst I'm coming at this from a point of self interest, getting the search results right will help the entire community.

S. Brett Sutton

![Screenshot from 2021-12-21 11-32-10](https://user-images.githubusercontent.com/900408/146851127-c054e6a7-e82a-4020-8eda-faa1c43bb4b0.png)

**Comment by isoos** [comment]
@bsutton: This seems like a bug, thanks for reporting, I'll look into it.

**Comment by bsutton** [comment]
Good to hear.
I was concerned it was working as intended.

And thanks for the prompt response.

S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by isoos** [comment]
It looks like that the search index didn't pick up the analysis scores properly after they have been ready, most likely because of this change:
https://github.com/dart-lang/pub-dev/pull/5356/files#diff-a0a0be2805ba4a671873a1acf18bad82b47f2fcba985cd85923686503f502ff1R60

The field is used here, but in the absence of the index it won't yield the packages in the index:
https://github.com/dart-lang/pub-dev/blob/master/app/lib/shared/task_sources.dart#L64

The search index has a roughly daily automatic update cycle, it should eventually trigger a refresh of the entry, and with that, it will update the score.

Note: (Until this is fixed in prod) each new published version will have a reduced score up to a day after being published, but will be auto-fixed after that (if no new version is published). Fixing the code shouldn't be hard (+ additional tests so that it won't happen again), but I'm not sure when we can get to deploy the fix, considering the holidays. (This bug is not mission-critical, e.g. `pub get` is not broken...)

**Comment by bsutton** [comment]
Thanks for looking into it.

Agreed, no need for an urgent fix.

Enjoy the break.

**Comment by isoos** [comment]
This fix has been deployed, and the search index should pick up new versions soon after they get analyzed.
