### ISSUE TITLE
Errors found after publishing but shouldn't be

### ISSUE THREAD

**Issue by alnitak** [dart-lang/pub-dev#5387]
Hi,
I have published a plugin and got some strange errors.
I did as usual the command
`dart pub publish`
I noticed the following problems:
 * Package compatibility is _[unidentified]_
 * The `Provide documentation` section has `Failed to run dartdoc` error
 * The `Support multiple platforms` has `Package resolution failed. Could not determine platforms.` error
 * The `Support up-to-date dependencies` has `The current SDK constraint does not allow the Dart version used by the latest stable Flutter (2.15.0)`

More info:
* I am using Flutter 2.15.1 
* I created the plugin project with `flutter create --template=plugin -a java --platforms ios,android,windows,linux,macos --description="Magnifying Glass" --org com.bavagnoli --project-name='magnifying_glass' magnifying_glass`

Here the link to the package on [pub.dev](https://pub.dev/packages/magnifying_glass)

<details open>
<summary>flutter doctor -v</summary>
<br>
[✓] Flutter (Channel stable, 2.8.1, on Manjaro Linux 5.10.84-1-MANJARO, locale en_US.UTF-8)
    • Flutter version 2.8.1 at /home/deimos/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (13 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/deimos/Android/Sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /home/deimos/Android/Sdk
    • ANDROID_SDK_ROOT = /home/deimos/Android/Sdk
    • Java binary at: /home/deimos/dev/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.0
    • cmake version 3.22.1
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/deimos/dev/android-studio
    • Flutter plugin version 63.2.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Manjaro Linux 5.10.84-1-MANJARO
    • Chrome (web)    • chrome • web-javascript • Chromium 96.0.4664.93 Arch Linux

• No issues found!
</details>

**Comment by isoos** [comment]
The issue is that `pub.dev` is slightly behind and not using the latest Flutter SDK yet (we don't have release during/around the holidays). Once we move forward, upgrade Flutter SDK on `pub.dev` (expected in early January) and will re-analyze the package (happens automatically, no action needed on your part), it will get better scores.

**Comment by isoos** [comment]
Note: the analysis failed because the `pubspec.yaml` constraint was on `sdk: ">=2.15.1 <3.0.0"`. If you don't need to use `2.15.1` and if you happen to release a new version because of a new feature, you may try to lower that constraint to `2.15.0`. Usually there is very little need to release a new version just because of the scores on pub.dev, but if you happen to bundle it with something new, go for it!

**Comment by alnitak** [comment]
Thank you very much!
