### ISSUE TITLE
Why do you need to check the package name for similar names?

### ISSUE THREAD

**Issue by SergeShkurko** [dart-lang/pub-dev#5473]
https://github.com/dart-lang/pub-dev/blob/ce53df80bdfbda1aa08c1b54e7ee9a8c898f78a1/app/lib/package/name_tracker.dart#L120-L126

I wanted to rename `native_pdf_view` to 'pdf_view' or 'pdf_viewer' packages for search friendly. 
But received
```
Do you want to publish ... 0.1.0 (y/N)? y
Uploading... (6.7s)
Package name is too similar to another active or moderated package.
```

https://pub.dev/packages/pdf_view (package 404)
https://pub.dev/packages/pdf_viewer (also 404)

Published packages has names: 
https://pub.dev/packages/pdfview  
https://pub.dev/packages/pdfviewer
but these packages have long been abandoned, still on version dart 1.0

Maybe it makes sense to _remove this check_ or _remove packages_ from pub.dev?
There is no information on how to contact the publisher

**Comment by isoos** [comment]
We've added the similar package name check to prevent confusion between two actively developed, but similarly named package (IIRC we have had a report on such package at that time).

In your case, the existing package is inactive, and in such cases it would make sense to allow the ownership takeover of the package. We have considered to facilitate such transfer of ownership via pub.dev, but until (and if) it happens, you can reach out to the owners of the existing package yourself. E.g. in once case, their github profile has an email, in the other case the `pubspec.yaml` in the package archive contains the `author` tag with the email. They can invite you as an uploader, and once you are an uploader, you can manage the package (e.g. remove them as uploaders).

Note: we have an upcoming release which should report back the name of the existing package which we've found as similar.

Also: `pub.dev` doesn't want to break projects by deleting packages that are or may be in use. Deleting a package is an exception for extraordinary circumstances, and we still reserve the name so that another developer cannot impersonate the prior publisher.

**Comment by SergeShkurko** [comment]
> E.g. in once case, their github profile has an email, in the other case the pubspec.yaml in the package archive contains the author tag with the email.

Thank you, I'll use your suggestion

>  we have an upcoming release which should report back the name of the existing package which we've found as similar.

What about adding ignoring the package name on matches if it is marked as `discontinued` / `unlisted` ?
Even if I can contact the owner and get the rights to the package `pdfview` it's not the same as `pdf_view`
Such a solution would allow creating packages with similar names only in case of refusal to support the package that first occupied a similar name

**Comment by isoos** [comment]
> What about adding ignoring the package name on matches if it is marked as discontinued / unlisted ?

That status may be reverted later on (e.g. after the transfer of ownership), and we could get into the same spot of two active packages having similar names.

**Comment by sigurdm** [comment]
The similarity check is in place to prevent typo-squatting. It is not perfect, but better than nothing.
