### ISSUE TITLE
Add `license` field to pubspec.yaml?

### ISSUE THREAD

**Issue by JKRhb** [dart-lang/pub-dev#5535]
Currently, there is no `license` field in the pubspec.yaml file, letting the display of licenses on pub.dev depend entirely on the content of the `LICENSE` file. This can lead to false positives if multiple licenses are included, some of which might be attributions to other projects.

To have more fine-grained control over what is actually going to be displayed on pub.dev, I wanted to suggest adding a `license` field to `pubspec.yaml`. Rust's package manager [cargo](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields) might be a good inspiration for the format of such a field: Here you can specify an SPDX-License-Identifier which will be displayed on the package repository crates.io.

The current license detecting approach used for pub.dev (see https://github.com/dart-lang/pana/issues/1015 for example) could then be adjusted to simply ensure that there license texts present for the defined licenses, giving the users themselves more control about the licenses they want to define. This would also solve the dual-licensing issue raised in https://github.com/dart-lang/pana/issues/997.

(I hope this is not a duplicate, I searched through the issue list but couldn't find a similar one.)

**Comment by isoos** [comment]
/cc @mit-mit 

I think that the current license detection in `package:pana` is very early-stage and so far we haven't really put much effort into measuring and/or improving its accuracy. We have plans to improve the multi-license classification, and/or fine-tuning thresholds...

I think it is better for users if we could just infer the license from the actual license text, but, at the same time, it is a legal text, and misclassification is worse than not classifying. In such cases the user-provided license declaration may be a good way to override it.

**Comment by jonasfj** [comment]
Our license detection is rather decent. @isoos you might be thinking of what we had a year ago.
We currently have a very low tolerance for mismatches. It could probably be tuned to detect more licenses instead of returning "unknown".

If we have a `license` property and a `LICENSE` file those can disagree.
In practice it's probably best to just include a `LICENSE` file, because that's the entire text.
And if the property and the file disagrees then you might have a legal quagmire (I'm no lawyer).
