### ISSUE TITLE
[!] Add a UNLIKE button, is important

### ISSUE THREAD

**Issue by ash0080** [dart-lang/pub-dev#5721]
1. Help to get better user feedback, reduce the time to find and evaluate the quality of third-party packages, currently only like, this is a quantity that increases with time, meaning that the earlier the package is published, usually has a higher rating, but not much related to its own quality;
2. Help maintainers get more realistic feedback;
3. Help to remove a lot of spam packages; For example, try searching "prompter" in pub.dev, You will get a surprise.

**Comment by jonasfj** [comment]
> 3. Help to remove a lot of spam packages; For example, try searching "prompter" in pub.dev, You will get a surprise.

How are these spam? useless yeah, very probably :rofl: 

In any case, moderation requests under https://pub.dev/policy should be sent to `support@pub.dev`.


----------------------------

An dislike button was under consideration when  the like-button was added. I think we opted not to do it because it invites abuse and bullying. I would argue that most useless packages don't accumulate a lot of likes, no matter how long ago the were published.

And I agree that we have a need for more metrics, better popularity metrics, maybe metrics from github, or more better static analysis, code coverage, etc. We do dream, but these things take time.

As for adding a dislike button, I'm not very inclined. I did have a crazy idea about adding a feature where publishers could label other packages as "reviewed" or "trusted", as a means of doing a quality stamp. But I fear that it's too complicated. So for now I'm just hoping we can add more small features / metrics, like better popularity metrics, maybe a graph of likes over time, or popularity over time. But to be fair, most of this is just loose dreams and hopes :D

**Comment by ash0080** [comment]
> > 3. Help to remove a lot of spam packages; For example, try searching "prompter" in pub.dev, You will get a surprise.
> 
> How are these spam? useless yeah, very probably 🤣
> 
> In any case, moderation requests under https://pub.dev/policy should be sent to `support@pub.dev`.
> 
> A dislike button was under consideration when the like-button was added. I think we opted not to do it because it invites abuse and bullying. I would argue that most useless packages don't accumulate a lot of likes, no matter how long ago they were published.
> 
> And I agree that we have a need for more metrics, better popularity metrics, maybe metrics from github, or more and better static analysis, code coverage, etc. We do dream, but these things take time.
> 
> As for adding a dislike button, I'm not very inclined. I did have a crazy idea about adding a feature where publishers could label other packages as "reviewed" or "trusted", as a means of doing a quality stamp. But I fear that it's too complicated. So for now I'm just hoping we can add more small features / metrics, like better popularity metrics, maybe a graph of likes over time, or popularity over time. But to be fair, most of this is just lose dreams and hopes :D

There are thousands of prompter_xxxx, which I believe is generated by a release script, do you really think it's the responsibility and obligation of a normal developer to email them one by one?

unlike is a simple solution, but of course you can also choose a 5-star rating system if you're worried about abuse, you mentioned a lot of optimizations above, but it doesn't seem like they're going to happen any time soon, does it? Then the current situation, where older packages have more like numbers, is not improved.

Ultimately, all the problems mentioned above are due to the poor search function of pub.dev.  It's not even as accurate as using google site:pub.dev xxxxx.

If google really cares about developers, it should be thinking about how to improve, not because xxx, we're not going to do it

**Comment by isoos** [comment]
> Ultimately, all the problems mentioned above are due to the poor search function of pub.dev. It's not even as accurate as using google site:pub.dev xxxxx.

Could you gives us a few examples where search did not work for you?

**Comment by ash0080** [comment]
> > Ultimately, all the problems mentioned above are due to the poor search function of pub.dev. It's not even as accurate as using google site:pub.dev xxxxx.
> 
> Could you gives us a few examples where search did not work for you?

OK, I'll take a practical example I recently encountered, I'm currently writing a package manager for dart/flutter

1.  First I had to find a base package, I searched for keyword 'command line', Please try to see how many pages the 'dcli' package is on, Incidentally, dcli has four full pages of 'depend on', Sort of a very popular package.

2. Next I would like to find a cli prompter package, You can try
'command line component', 'command line prompt', and see how long it takes to eventually find the package 'interact'

**Comment by ash0080** [comment]
> Thank you, that is incredibly helpful for fine-tuning parts of the ranking.

You're welcome, I really want pub.dev to be more usable
