### ISSUE TITLE
Speed up deploys: reuse an image?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dev#593]
`gcloud app deploy` has a `--image` argument.

Pondering: do the first deploy "normally" – parse out the Docker image that's created.

When deploying the 2nd and 3rd, reuse that image. (Assuming that the configuration is not baked in.)

We'd save the Docker build time for the latter ones...right?

**Comment by isoos** [comment]
I believe docker caches the images locally, and the caching should happen by default.

Btw. [on the app deploy ref page](https://cloud.google.com/sdk/gcloud/reference/app/deploy) there is only `--image-url`, and I'd assume that specifying that wouldn't affect docker caching.

**Comment by kevmoo** [comment]
The image build and cache is remote – AFAIK. You don't need docker locally to deploy any more.

You'll see that build runs 3x – it need not

**Comment by sortie** [comment]
Deploying pub continues to be very slow. It'll reduce my workload a bunch if it can be sped up.

Likewise deleting old app engine version seems very slow as well. I think it's possible the delay is due to some shut down actions rather than a fundamental aspect of app engine. Could that be right? That may be another issue.

**Comment by isoos** [comment]
@jonasfj did improve the staging deploy. I have no idea if prod deploy can be helped the same way. wdyt @jonasfj?

**Comment by jonasfj** [comment]
Build time does not dominate deployment time. The biggest speed-up in deployment time was to update and existing version, instead of creating a new version, we can't do that in production for risk of dirty deployments..

We could script up something to do this. But I only think it'll shave a few minutes of our 1 hour deployment.

The fact that staging is fast is more important, I suggest we close this. If we wanted to make deployments to production fast, we're better off moving to a different platform that "AppEngine Flex", or wait for "AppEngine Flex" to become faster :)
