### ISSUE TITLE
Respect search filters even for exact name matches

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dev#5948]
We currently show both Dart 1.x and Dart 2.x packages in search, and then tag the Dart 2 incompatible packages:

I'd like to change this so that we:
- Hide Dart 2 incompatible by default
- Add a new 'Advanced > Include Dart 1.x` option, which reverts to the current behavior where both 1.x and 2.x are shown.

**Comment by mit-mit** [comment]
Hmm, sounds like this was a misunderstanding -- we already hide Dart 1.x packages. It was based on the behavoir of a search like this:
https://pub.dev/packages?q=chart

The first listed hit here is a Dart 1.x package. It turns out this is the case as it's a perfect name match; in those cases we ignore the filtering.

I suggest we change this so that filters are always respected. If you want to get to a filtered package via name, you can edit the Url manually to `/packages/<name>`.

**Comment by sigurdm** [comment]
After more offline discussions I think we agree here.

Let's remove the exact matches and see how it goes.

**Comment by isoos** [comment]
The following updates have been implemented and deployed:
- we no longer expose the exact name match if it does not match the search filters
- we promote the exact name match to the first place if and only if it is in the default search scope (e.g. no sort, no ownership scope, not extra tag predicates)

I think the later is a bit limiting, and based on an unexpected search result, I think the exact name match to be promoted even when we have tag predicates (e.g. `show:unlisted`) - while still only doing that when the package otherwise matches the query conditions.
