### ISSUE TITLE
"Dart 3 compatible" is a lie. There is no cake!

### ISSUE THREAD

**Issue by JCKodel** [dart-lang/pub-dev#6727]
I was using https://pub.dev/packages/equatable_lint with https://pub.dev/packages/isar_generator, both "Dart 3 compatible".

The problem is: equatable_lint requires https://pub.dev/packages/custom_lint/versions/0.2.12 (which is also marked as Dart 3 compatible).

But, with custom_lint 0.2.12, somehow, `dart run build_runner build` don't recognize any Dart 3 feature and issues exceptions of syntax errors in features like `final class`, `switch` statements and says that records are available only as an opt-in in analyzer.yaml! It seems it is running somehow in Dart 2 mode. Don't ask me why or how.

After making a pull request to equatable_lint upgrading the https://pub.dev/packages/custom_lint_builder/versions/0.2.12 (which is also marked as "Dart 3 compatible") to https://pub.dev/packages/custom_lint_builder/versions/0.4.0 (latest), all issues are gone.

So, all versions of all packages are Dart 3 compatible, yet, it breaks some other functionality specifically ignoring all Dart 3 new features.

**Comment by isoos** [comment]
@JCKodel: Is my understanding correct that when you say something ignores Dart 3 features, it is one of the packages that you've linked running as a package analyzer? pub.dev can only say that you can run them on Dart 3, but it can't know what the package does, that specifically it analyses Dart 3 and whether that analysis is correct.

**Comment by JCKodel** [comment]
The problem is: currently, that's useless because some packages clearly have issues with Dart 3. So the badge, per se, has no value (at least in my POV).

What is exactly the current value of "Dart 3 compatible" for you?

It would be a lot nicer if those badges showed the min SDK version (so `environment: SDK: ">= 3.0.2 <4.0.0"` show some "Dart 3.0.2" badge, or "Dart 3.0"). 

It would be even nicer if I could specify my environment constraints in the search, so, if for some reason I'm using some old SDK, I could filter not only for packages that run on those constraints, but the latest version of the packages, considering those constraints.

For example: I have projects running Flutter 1.22.4 and 2.5.3 (sdk: ">=2.9.0 <3.0.0") (which I cannot upgrade without a huge cost). Which version of, let's say, `google_sign_in` works on those constraints?

That would make a "Dart 3.0 compatible" badge a lot of value because, if the SDK constraint is >= 3.0.0, then you know that will actually work on Dart 3.0.

Does this make sense for you?

**Comment by isoos** [comment]
> What is exactly the current value of "Dart 3 compatible" for you?

The label means its face value: you are able to use it with Dart 3. Dart 3 compatibility is more than the `^3.0.0` constraint, you may use compatible packages with `>=2.12.0 <3.0.0` constraints too (I have a two years old package with that constraint that we are using with Dart 3).

In the absence of the label it is likely that you are unable them with Dart 3. I'm sorry that the specific analysis packages in question cause you issues, and its lack of feature and out badge is somewhat confusing. However, you must contact their authors, because pub.dev can't verify the claim of their features, and the Dart 3 compatible badge is useful for many packages.

> For example: I have projects running Flutter 1.22.4 and 2.5.3 (sdk: ">=2.9.0 <3.0.0") (which I cannot upgrade without a huge cost). Which version of, let's say, google_sign_in works on those constraints?

You can check the minimum Dart SDK constraint on the https://pub.dev/packages/google_sign_in/versions page, that should give a rough indication on the likely version. I think `flutter pub upgrade` should upgrade you to the latest still-compatible version though. At the same time, the pub.dev site is always tracking the latest stable versions, and the site encourages developers to keep their packages and their dependencies up-to-date. It is outside of its scope to support search with dependency graph resolutions, that's the scope of the local `pub` client.

**Comment by sigurdm** [comment]
The Dart 3 label is static-analysis based only, as is any scoring we provide.

`custom_lint` does **run** under dart-3 (but it still only analyzes dart 2 code). 🙈

Whether the package actually works is undecidable in general. I think that premise is acceptable.

Consider filing an issue with custom_lint to implement support for the new language features.
