### ISSUE TITLE
[FR] Roll runtime artifacts automatically

### ISSUE THREAD

**Issue by AlexV525** [dart-lang/pub-dev#6938]
Now we roll artifacts for the runtime manually. For example:
- https://github.com/dart-lang/pub-dev/commit/3b2986d53449dffc633ca49bdbaa628604eec006

We should do this automatically and periodically by fetching the storage bucket API and determine which version we should use. This will free ourselves from being reported for outdating analysis and reduce the chance to meet exceptions.

(As per discuss in https://github.com/dart-lang/pub-dev/issues/5352)

**Comment by jonasfj** [comment]
There is some concerns here:

## (A) Security
Security concerns are mostly a matter of compliance with policies, and probably getting appropriate exemptions or doing the required verification.

A lot of this is just paper work (I hope). Since we run analysis in isolated per-package VMs, risks are somewhat limited.

## (B) Ability to rollback traffic
Today, a deployment of pub.dev has a `runtimeVersion`. The `runtimeVersion` covers analysis results and some data structures in cache and datastore.

When we make a deployment of pub.dev, we can migrate traffic back to previous version of pub.dev. And when doing so pub.dev will show analysis results + dartdoc that was generated by the `runtimeVersion` the previous version had.

We don't always bump `runtimeVersion` when making a release of pub.dev; but do this whenever we bump the Dart or Flutter SDKs.

If we dynamically download the latest Dart / Flutter SDKs and use them for analysis, we'll have no recourse if things stop working. As things are today, we can simply migrate traffic back.
True, when this happens we won't have the latest version of the Dart / Flutter SDK doing analysis.

Mostly, this is not a problem because we a deployment prior to a Dart or Flutter release. But sometimes (as was the case around Dart 3.1), we didn't the launch out ahead of time, and when the launch happened we found issues that needed to be fixed.

Not having analysis with the latest Dart / Flutter stable SDK is sad, but it doesn't affect most packages.

----------------

## Alternative solution (1): Force analysis with latest prerelease

An alternative solution we've considered is to allow whatever prerelease of the Dart / Flutter SDKs we have to do analysis for a package that requires the next stable version of Dart or Flutter SDKs.

It's not pretty, but in most cases it won't happen. And when it does the scoring package will still show what version of the SDK actually did the analysis. And the prereleases we have when close to a Dart / Flutter SDK release is often closely aligned with the final release.

Technically, it'll require a hack to the pub solver to do this. Mostly just setting an environment variable or something like that to make it think that it has the latest stable version of the Dart SDK.

The only reason it doesn't work today is that packages that say: `sdk: ^3.1.0` in the `pubspec.yaml` cannot be used with an SDK that has the version `3.1.0-dev`. But if allowed `pub` to pretend to be the next release with an environment variable  `PUB_IMPERSONATE_NEXT_STABLE=true`, that would be easy to do.

Requires:
 * A tiny hack in `pub`,
 * A tiny hack in `pkg/pub_worker/` in this repository (and maybe `pana`).


## Alternative solution (2): Download latest stable / prerelease when necessary only

We could also tweak `pkg/pub_worker/` to download the latest stable or latest prerelease when the built-in stable version of the Dart SDK doesn't satisfy the SDK constraint of the package we have to analyze.

This is probably acceptable wrt. (B), it would limit our ability to rollback to a previous version. Since rolling back wouldn't fix issues for packages that requires a new Dart SDK for analysis to work. But these packages are also prone to fail analysis now.

**Comment by isoos** [comment]
We have implemented the alternative solution (2) - downloading the latest stable/prerelease only when it is needed.
