### ISSUE TITLE
package score wrong with flutter path not found

### ISSUE THREAD

**Issue by techwn** [dart-lang/pub-dev#7264]
I found my package has wrong score with hint:
```
Found no Flutter in your PATH. Could not determine the current Flutter version.
```

you can check package like these:
https://pub.dev/packages/sliver_sticky_collapsable_panel/score
https://pub.dev/packages/fluttery_framework/score

even the top package:
https://pub.dev/packages/path_provider/score
https://pub.dev/packages/url_launcher/score

**Comment by sigurdm** [comment]
Seems to be the same as: https://github.com/dart-lang/pana/issues/1294

**Comment by sigurdm** [comment]
This seems to only be a problem in our latest deployment.

For now I have rolled traffic back...

**Comment by isoos** [comment]
I think I've found some partial explanation on why this is breaking now:
- Flutter stores the tool state in `~/.config/flutter/tool_state`. An example is like this:
```{
  "is-bot": false,
  "license-hash": "dc96c9af3fbf254412ffc24bd11a3dc4",
  "last-active-master-version": "b60c855af5150b695638b2195f500d3c003b71ab",
  "redisplay-welcome-message": true,
  "last-active-stable-version": "796c8ef79279f9c774545b3771238c3098dbefab"
}
```
- It will re-display the welcome message if the license terms has changed since the last run:  https://github.com/flutter/flutter/blob/7d9f2082f1b069d46b33005f8e7b090875ec4df0/packages/flutter_tools/lib/src/reporting/usage.dart#L338-L339
- The `license-hash` value changes from `3.16.2` (`595d1dceffbb08773627ff5766d17ddf`) to `3.18.0-0.1.pre` (`dc96c9af3fbf254412ffc24bd11a3dc4`).
- As the dockerfile initialized the pre later, and then the analysis worked with the stable, it may have triggered the welcome message.

**Comment by isoos** [comment]
The fix has been deployed and it seems to be working.

**Comment by sufftea** [comment]
Seems to be broken again.

**Comment by isoos** [comment]
@sufftea: which package seems to be broken?

**Comment by sufftea** [comment]
The ones from the original post, plus mine https://pub.dev/packages/hyper_router/score
