### ISSUE TITLE
Analysis issue with package using WebSocket

### ISSUE THREAD

**Issue by KammererTob** [dart-lang/pub-dev#7327]
I noticed that my released package suddenly has a "Analysis issue". I have not pushed any new code or updates so i am not sure where this is coming from.

Link to my package: https://pub.dev/packages/stomp_dart_client

This is the error it displays:
![image](https://github.com/dart-lang/pub-dev/assets/1510949/ee788606-bbfb-46d7-938b-4417fc4aa8a1)

Executing the reproduction mentioned here does not lead to any issues (using lints: ^3.0.0):

```bash
$ dart analyze lib/src/_connect_html.dart
Analyzing _connect_html.dart...
No issues found!
```

Is this an issue on my end? If so, what are my options to resolve this? Thanks!

**Comment by isoos** [comment]
The dependency `web_socket_channel` had a recent new release: https://pub.dev/packages/web_socket_channel/versions 
Maybe it has a breaking change there?

**Comment by KammererTob** [comment]
Yes. That seems to be the issue. But why does a version upgrade in another package affect my released package? My last release was 3 months ago. That breaking change in `web_socket_channel` should probably have been a new major version?

**Comment by isoos** [comment]
> That breaking change in web_socket_channel should probably have been a new major version?

Yes it should have. Maybe contact them about it, it always help to get to know other developers we depend on, and maybe they do not know the use case that they were breaking.

> But why does a version upgrade in another package affect my released package?

We do re-analyze packages periodically and also when their dependencies are updated, because the analysis should always reflect the latest stable versions. After all, users of your package do use the combination of your package and its dependencies.
