### ISSUE TITLE
Is Pub.dev down?

### ISSUE THREAD

**Issue by adityarath302** [dart-lang/pub-dev#7400]
* Explain the issue,
 * Using bullet points!
 * Link to screenshot.

```dart
PING pub.dev (216.239.38.21): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
```

```dart
Downloading Darwin arm64 Dart SDK from Flutter engine 6e2ea58a5ccbefcfadc2d4b7b8045fc6c20ab812...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  207M  100  207M    0     0  10.9M      0  0:00:18  0:00:18 --:--:-- 12.4M
Building flutter tool...
Resolving dependencies... (13:03.7s)
```

**Comment by isoos** [comment]
@adityarath302: pub.dev works for me (Hungary). What's your location, ISP and setup? Can you also run this script for further debugging?
https://github.com/dart-lang/pub-dev/blob/master/app/bin/tools/check_domain_access.dart

**Comment by adityarath302** [comment]
@isoos 

Testing host resolves...
- pub.dev IPv4 resolve and connect succeeded: 0 / 4
- pub.dev IPv6 resolve and connect succeeded: 0 / 4
- pub.dartlang.org IPv4 resolve and connect succeeded: 1 / 1
- pub.dartlang.org IPv6 resolve and connect succeeded: 1 / 1
- storage.googleapis.com IPv4 resolve and connect succeeded: 16 / 16
- storage.googleapis.com IPv6 resolve and connect succeeded: 16 / 16
Testing one connection per request...
Unhandled exception:
TimeoutException after 0:00:15.000000: Future not completed

**Comment by isoos** [comment]
It looks like some kind of block is in place that prevents you to resolve and connect to `pub.dev`. What country are you in, what ISP?

**Comment by Sameer738** [comment]
Same issue with me also 
i'm from India and ISP is BSNL

I/flutter (25725): Testing host resolves...
I/flutter (25725): - pub.dev IPv4 lookup failed: SocketException: Failed host lookup: 'pub.dev' (OS Error: No address associated with hostname, errno = 7)
I/flutter (25725): - pub.dev IPv6 lookup failed: SocketException: Failed host lookup: 'pub.dev' (OS Error: No address associated with hostname, errno = 7)
I/flutter (25725): - pub.dartlang.org IPv4 lookup failed: SocketException: Failed host lookup: 'pub.dartlang.org' (OS Error: No address associated with hostname, errno = 7)
I/flutter (25725): - pub.dartlang.org IPv6 lookup failed: SocketException: Failed host lookup: 'pub.dartlang.org' (OS Error: No address associated with hostname, errno = 7)
I/flutter (25725): - storage.googleapis.com IPv4 lookup failed: SocketException: Failed host lookup: 'storage.googleapis.com' (OS Error: No address associated with hostname, errno = 7)
I/flutter (25725): - storage.googleapis.com IPv6 lookup failed: SocketException: Failed host lookup: 'storage.googleapis.com' (OS Error: No address associated with hostname, errno = 7)
I/flutter (25725): Testing one connection per request...

**Comment by Sameer738** [comment]
@isoos 
Same issue with me also
i'm from india and Isp is BSNL

Testing host resolves...
- pub.dev IPv4 lookup failed: Unsupported operation: InternetAddress.lookup
- pub.dev IPv6 lookup failed: Unsupported operation: InternetAddress.lookup
- pub.dartlang.org IPv4 lookup failed: Unsupported operation: InternetAddress.lookup
- pub.dartlang.org IPv6 lookup failed: Unsupported operation: InternetAddress.lookup
- storage.googleapis.com IPv4 lookup failed: Unsupported operation: InternetAddress.lookup
- storage.googleapis.com IPv6 lookup failed: Unsupported operation: InternetAddress.lookup
Testing one connection per request...

**Comment by adityarath302** [comment]
@Sameer738 I have the same BSNL ISP and it's not working. Please tag them on twitter and ask them to do the needful.

**Comment by Sameer738** [comment]
@adityarath302 
Temporary Solution for now : 

flutter pub get' tries to fetch your plugins that you have declared in your pubspec.yaml and by default it makes a GET request to pub.dev or https://pub.dartlang.org/. So if either https://pub.dartlang.org/ or storage.googleapis.com is blocked by your isp or your company's firewall you wont be able to complete packages get & hence wont be able to build your flutter project. Rather than using the vpn, I prefer using a mirror repository. You can simply change or set two environment varibles with a mirror link like mentioned below. After that 'flutter pub get' command will try to fetch your packages from the specific mirror link. The variables and the links are - * PUB_HOSTED_URL=https://pub.flutter-io.cn/ * FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn/

For windows, use these commands in cmd to set the variables in your project environment:

set PUB_HOSTED_URL=https://pub.flutter-io.cn
set FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
Make sure to apply these commands in your project directory in cmd and use 'flutter pub get' from that specific cmd. You can check if the variable is set or not by applying:

echo %PUB_HOSTED_URL% 
The output should be the URL that you just set.

These variables are set only for this environment and will be cleared when you close this terminal. So for windows, if you set these variables in your system user environment then you will be able to use 'flutter pub get' and fetch packages from the china mirror sites at any time.

For mac, export the variables in your bash_profile like this:

 export PUB_HOSTED_URL=https://pub.flutter-io.cn
 export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
After this you should be able to apply flutter pub get successfully. (remeber to source your bash_profile after setting a variable)

After all this, if you still can't get the packages: * Delete pubspec.lock file from your project. * Restart your PC. * Check by using echo command to see PUB_HOSTED_URL & FLUTTER_STORAGE_BASE_URL environment variables are set properly or not.

If these variables are set, flutter sdk will try to fetch packages from the mirror site you have set by this variable. If these variables are not present in the workspace environment then flutter sdk will try to fetch the packages using its default urls mentioned earlier.

Hope you will be able to get the packages now without a vpn and anything else. Best of luck.

**Comment by jonasfj** [comment]
Have you tried using a different DNS server? like `8.8.8.8` https://developers.google.com/speed/public-dns

**Comment by jonasfj** [comment]
Closing this as I see nothing actionable.

If this persists or happens for other ISPs, feel free to let us know.
Though, I'm not sure there is much we can do.
