### ISSUE TITLE
How to increase the limit?

### ISSUE THREAD

**Issue by anchao-lu** [dart-lang/pub-dev#7610]
The "search" operation is blocked, as its rate limit has been reached (120 in the last 2 minutes). Please try again later. Please report the issue on https://github.com/dart-lang/pub-dev/issues/new if you think the limit should be increased to accommodate your use case.

**Comment by isoos** [comment]
@anchao-lu: What are you doing to reach that message?

**Comment by anchao-lu** [comment]
> @anchao-lu: What are you doing to reach that message?

Just general search plugin

**Comment by isoos** [comment]
Please add delayed search into the plugin when typing (e.g. start search only after typing stopped for several minutes or enter was hit). Otherwise the app will issue way too many useless search requests (because they are discarded).

Are you search for package names only? You may also fetch the package names in a single request and do the search on that dataset locally.

**Comment by jonasfj** [comment]
Yeah, please don't use the search functionality in a plugin. I'm not confident the service will gracefully handle incremental search queries -- hence, why we made some extremely crude rate-limits :see_no_evil: 

We do have a API end-points for enabling auto-completion of package names, see:
https://pub.dev/help/api
