### ISSUE TITLE
pub.dev returning 401 on `dart pub get` in Github Actions CI due to invalid tokens

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/pub-dev#7623]
Starting about 7 hours ago, our CI started hitting failures on `dart pub get` due to the https://pub.dev server returning a 401. We use the dart-lang/setup-dart@v1 action, which detects the `ACTIONS_ID_TOKEN_REQUEST_URL` and `ACTIONS_ID_TOKEN_REQUEST_TOKEN` environment variables and uses them to automatically create and add a pub token with `dart pub token add --env PUB_TOKEN`. The creation of that pub token has been happening for a while, but as of this morning those tokens started being rejected by the pub server.

Some related notes/thoughts:

- We noticed that the dart-lang/setup-dart action had a release about 5 hours ago, but we tried pinning to previous releases of that action with no success.
- We see this on internal runners as well as the public github runners for public repos.
- We see this on Dart 2.19.6 as well as the latest Dart stable

---

Here's an example failure: https://github.com/Workiva/dart_dev/actions/runs/8514912591/job/23626172926

---

Has anything changed recently on the backend that might be related to our tokens being rejected with a 401 now?

**Comment by chrisgustavsen-wf** [comment]
```
Resolving dependencies...
Invalid token for https://pub.dev/ deleted.
Authentication error (401)
```

**Comment by Jordan-Nelson** [comment]
I am seeing this failure as well. 7 hours ago is the earliest failure I see. I don't see it failing on all jobs. I don't see a clear pattern on which jobs it fails on though. Here is an example of one of the failures: https://github.com/aws-amplify/amplify-flutter/actions/runs/8616233428/job/23613401799

Let me know if you would like more info.

**Comment by Jordan-Nelson** [comment]
The command that fails for us is activating a local package. It seems to fail when doing this with the dart CLI (`dart pub global activate -spath <path>`) but succeeds with the Flutter CLI (`flutter pub global activate -spath <path>`)

**Comment by jonasfj** [comment]
> The command that fails for us is activating a local package (this is one of the first steps in all of our CI jobs).

Please file a separate issue, this is most definitely unrelated to 401 when trying to publish.

See also https://github.com/dart-lang/pub-dev/issues/7624, however, that is unrelated to 401 issue with automated publishing.

**Comment by jonasfj** [comment]
digging around we found that new URLs serving archives directly from GCS using GCLB causes issues.
```
curl -H 'Authorization: wrong' -sv https://pub.dev/api/archives/retry-3.1.2.tar.gz -o /dev/null
```

because the pub client will send an authorization header when a token is available.

**Comment by jonasfj** [comment]
We recently changed package URLs to be served from GCS through GCLB, instead of redirecting to GCS. Allowing us to enable caching of package archives in Cloud CDN.

This works great, but if you attach an `authorization` header to the request to GCS (through GCLB), GCS will reject the request 401. But if someone from similar location already requested the file without an `authorization` header earlier and it's sitting in Cloud CDN, then you'll get that response. Hence, the issue becomes intermittent.

Solution was to configure GCLB to strip `Authorization` headers when rewriting requests to GCS.

This wasn't a problem when we redirected the `pub` client to download directly from GCS. Because it would redirect to a different host, and the `pub` client will not include an `Authorization` header for hostA, when making requests to hostB -- even it redirected from hostA --- we think that was a reasonable security posture to take.

------------------

We believe this to be fixed now. Sorry for the inconvenience.
