### ISSUE TITLE
Analysis issue, Dart 3 incompatible package is Second Result - Should we push it down in search rank results?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub-dev#7865]
URL: https://pub.dev/packages?q=authentication

I searched for "authentication", and I saw:

![Screenshot 2024-07-11 at 11 49 23 AM](https://github.com/user-attachments/assets/b7c85588-c387-44d0-bf36-a0eb60a22fb8)

Observation:

* the second result in the ranked list doesn't look very trustworthy.

Insight:

* this can lead to a potentially false impression that pub has a lot of unmaintained packages. if the second result for a common term is a "old unmaintained package", then what about the other results?

Suggestion:

* Push packages with analysis errors or Dart 3 incompatible down in search results. Or, hide them (you have to opt-in to "show me packages with analysis errors" and "show me packages incompatible with Dart 3")

Hypothesis:

* If we do that, then trust in pub will go up, as users will see maintained packages more often, and they will stop seeing unmaintained/old/outdated/analysis-issues in top results, which will improve their perception of the pub ecosystem.

**Comment by isoos** [comment]
This is an exact package name match, and it is automatically promoted to the top (after the SDK results if there is any).

I'm not sure if would help ranking these down, as previously it was an explicit request from users that we should expose such packages at the top.

**Comment by FMorschel** [comment]
One idea I had was to simply place one new checkbox at the left that would be something like "Show only packages with no analysis issues" (probably a simpler name but that would be the intent).

And something else I was thinking. Is there any way for the website to save "user preferences"? That check (and maybe Dart 3 compatible) could be set there so that every time someone (logged in or by the browser-specific setting) searches for anything those filters are set.

> This is an exact package name match

In cases like this, we could create a warning or at least place a more compact version for the package tile. The compact version could also be used for SDK results that are promoted today.

**Comment by isoos** [comment]
With the recent adjustments for the results from the SDK libraries, the result page is cleaner: we have the exact name match as the top result, which is to be expected, and the rest coming along after that. The package, while not Dart 3 compatible, seems to have some use, so completely hiding may not be an ideal option for all users looking for it.

**Comment by FMorschel** [comment]
Sorry, I don't think I was clear enough. 

---

First, let these two options for "No analysis error" and "Dart 3 compatible" by themselves on the left. Above the collapsing groups or in a new collapsing group just for them, and for that group to be opened. Such as the platforms one is today.

That would ensure the user can see what is being "hidden".

---

Secondly, regarding the exact name result, I prefer the suggestion of simply creating a more compact version of the tile to show even when these specific checks don't allow it.

Also, I believe that there could be something else (even today) to indicate that the result with the exact name match is at the top simply because of that. Something like a different background colour or something similar.

I agree that hiding it would not be ideal, and with the right checks marked today, it does that anyway. Of course, currently, it adds the test to the search, but if the user has checked anything previously, changed the text, and they are still looking for the exact name match, they have no indication that such a package exists.

See this with no checks:
![image](https://github.com/user-attachments/assets/1e156b60-aeb2-4c4d-9bc0-b3bc147dda6e)

See this with "Dart 3 compatible" checked:
![image](https://github.com/user-attachments/assets/f57f633b-f488-46f2-947f-0ca54c0f9eea)

---

Lastly, I also suggest that there could be some form of saving (mainly/only these) checkbox states between sessions. Since we want to move forward with our ecosystem, if someone has no old projects and/or has recently joined the community, it makes no sense for us to keep showing them something they can't use. If they still want to see something outdated or with analysis issues, they can simply uncheck the options at any given time.

**Comment by sethladd** [comment]
I see the challenge here.

* some people might use the pub search as a "bookmark" feature, using search to "get to that package by name"

* other people might use the pub search to explore, and using search to "give me a ranking of all options that match the subject matter I am searching for"

In the former, I can see why we want to optimize for "exact match wins and is first result, no matter any other ranking signals".

In the later, I can see an argument for using opinionated ranking signals to inform rank order, such as "is Dart 3 compatible?" and "no analysis errors?" and "is a Favorite package" and "has high score" etc etc

+1 to the idea that we find ways to see the options under "Advanced" as those look really really useful. Consider:

* less "Advanced" more "Filters", as "Advanced" sounds scary and 'you probably don't want this unless you really really know', and "Filters" is more "Go here and filter down the results". I assume we want to make it easy to find Favorites and Updated, so I would guess those are less Advanced and more Encouraged filters.

* default to "see all filter options currently under Advanced", instead of what appears to be the default of "Advanced is auto closed"

Regardless, I'm glad that dart:html no longer is the top result for "authentication", thanks for fixing that!

**Comment by sigurdm** [comment]
I suggest showing direct name matches "out of band" (ie. not in the regular list of results):

Something like this mockup:
![image](https://github.com/user-attachments/assets/9e4a0164-827b-4a51-ac25-6ba67b1008d0)

**Comment by FMorschel** [comment]
The last comment by @sigurdm is similar to how things are showing up for me today (it doesn't show that it is incompatible, version and time, but it is similar). Thanks a lot!

**Comment by sigurdm** [comment]
Yeah - I think the recent changes have fixed this.

@isoos do you think we can close this?

**Comment by isoos** [comment]
Yeah, this has been fixed.
