### ISSUE TITLE
Analysis issue

### ISSUE THREAD

**Issue by vishnudas-bluefox** [dart-lang/pub-dev#8211]
# Environment

- Dart version (run `dart --version`):  3.5.4
- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"): linux_x64
- Are you using the Chinese community mirror or a corporate firewall? No

# Problem

  Why unwanted reducing in package points

```yaml
<copy/paste pubspec.yaml>
```

## Expected behavior

The flutter package analysis is raising error on flutter base files 😆 

## Actual behavior

![Screenshot ](https://github.com/user-attachments/assets/0b5b71b8-910f-4bf9-9952-e93e9fb4a521)

## --trace output

```

```

**Comment by sigurdm** [comment]
What is the package name?

**Comment by isoos** [comment]
The package is https://pub.dev/packages/material_charts and the issue seems to be that `pana` reported issue in the `lib/example/analysis_options.yaml` file. It seems to me that the `lib/example` directory was used instead of the `lib/` being the source of the package and `example/` as a separate project. The files from the author's repository seem to be deleted around the 0.0.19 version:
https://github.com/vishnudas-bluefox/material_charts/commit/35d6e371b3c19785b43789e6103140b8bf770a30

@vishnudas-bluefox Please follow the layout conventions as described here: https://dart.dev/tools/pub/package-layout

I'm closing the issue as we don't seem to have any action on it.
