### ISSUE TITLE
Web Support detection Mechanism is FAILING for ISAR package

### ISSUE THREAD

**Issue by espinal1976** [dart-lang/pub-dev#8221]
ISAR packages is published to have support for web. When it does not. 
I have just wasted 800 hours of work thinking this package will allow also web functionality. And just saw a message from the maintainer say that the implementation for WEB is not done. Is not even in the roadmap. here is the message from @simc https://github.com/isar/isar/discussions/1143
So I am sure you detection mechanism has failed or has been some how tweak by these developers.
I would like noone else tossing 800 hours of work because of a TOTALLY WRONG publishing.

**Comment by isoos** [comment]
@espinal1976 @simc: The package has a special rule that says to replace on library import with another if the target is the web platform:
https://github.com/isar/isar/blob/main/packages/isar/lib/isar.dart#L10-L11

Authors should use this only if they actually do provide support for the web platform, otherwise, they should rather not have a special case like that. E.g. we would have the same analysis result if all the web-specific library would do is `throw UnimplementedError()`.

Alternatively, if the package is known to not support the platform web, they could just list the supported platforms as described here: https://dart.dev/tools/pub/pubspec#platforms

---

@sigurdm @jonasfj: Do you see any actionable thing here?

One thing that is worth to mention: wasm-support, because it uses different conditional imports, detects the ffi use correctly.

<img width="605" alt="image" src="https://github.com/user-attachments/assets/2deb1a5c-a825-424d-a432-4bce1c9300f8">

**Comment by sigurdm** [comment]
No I don't think we can really do much here, except suggest that the author updates their package.

**Comment by espinal1976** [comment]
So can I basically write a package and put that it support everything in your platform and mislead every body.

And make every body waste tons of hours?

John A.

**Comment by isoos** [comment]
@espinal1976: Besides the conditional import being wrong, I don't see any malicious or intentionally misleading part, neither in the linked issue, nor in the code. Yes, they could be more precise and fix the package either via pubspec or the import, but other than that, to me this seems to be a honest mistake. I would imagine that you could contribute the pubspec update to the package and get it merged. 

Having said that, I feel your pain, and it is really unfortunate that the package author is not that responsive. However, from the analysis point of view, this is the most we can say or do, and in practice you cannot expect every author to support and fix all the bugs all the time.

And yes, you could publish a package that says it does something while lying (either by not doing it or doing completely different or malicious). Yes, it is possible to make sure that static analysis won't catch you doing it (neither ours nor any different analysis), because the malicious part is only apparent at runtime. I don't think there is any generic solution for this problem. Any static analysis has limits. However, in most cases, trying things out should reveal the trivial shortcomings and lies fast enough.

**Comment by sigurdm** [comment]
I don't think we'll take further action here.

Thanks for reporting
