### ISSUE TITLE
Support custom package images

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dev#882]
See https://github.com/dart-lang/pub-dartlang-dart/pull/881

Would be great if we could show a custom image for a package in search listings.

Question: should it be a URL? Part of the package?

Not sure we want package upload/download to get bloated w/ content.

Pondering: we could update the pub client to upload the image (if it's in the pubspec) as a separate item.

If we had a package convention for this (put it under `/docs/logo.png`) then we could help address https://github.com/dart-lang/pub-dartlang-dart/issues/850

We can 'host' the logo as an asset under the pub site `packages/<pkg>/logo.png` and let folks use relative links that align w/ their readme.md

**Comment by kevmoo** [comment]
...maybe just a URL would be good? Require it be absolute?

Not sure if we should do processing on it for size...

**Comment by isoos** [comment]
I've been checking some packages with logos (like angular and aqueduct), and it seems that for the logo to work across github, pub site and their custom homepage, they'd put their logo:
- as the first image in the `README.md`,
- with an absolute URL,
- before any other content.

It may be a raw content URL on github, or a file hosted on S3. There is no benefit packaging the file inside the package archive, because then all of the cached copies would need to handle that, taking up much more space than the package itself. 

We could introduce a `logo:` property in `pubspec.yaml`, and in the absence of that, detect the first image in the README.md and use it as logo.

I wouldn't necessarily store the logo itself on the pub site, but if we want to protect the users from third-party server outages and missing logos, we could do a smart pass-though caching of the image. For example, under the `/packages/[package]/logo.png` URL we could fetch the original content, store it in memcache and serve it. But this is not necessary in the first part of the implementation.

Question: where do we want to display such logo?

**Comment by kevmoo** [comment]
> Question: where do we want to display such logo?

As part of the package metadata when a package is shared on twitter,facebook, etc. – that's the big one for me.

I could imagine also showing a logo on the search results page - https://pub.dartlang.org/packages – maybe...

**Comment by isoos** [comment]
> As part of the package metadata when a package is shared on twitter,facebook, etc. – that's the big one for me.

I think it is reasonable to use the first image in the readme for that.

I think there is at least one reason to not introduce a separate `logo:` entry in `pubspec.yaml`: those who would use it will be including the logo in their readme anyway.

> I could imagine also showing a logo on the search results page 

I'd start with the metadata for sharing, and we can experiment with the search results later. It would probably require some kind of standardization about the dimensions and how we shrink/crop/scale the image if it is larger.

**Comment by kevmoo** [comment]
I'm nervous about using the first image in the readme. Making sure that it's a image folks want to use could be tricky. Also, avoiding badges.

Let's hold off here. Getting docs done is higher priority IMHO

**Comment by mit-mit** [comment]
I'd like to see a UI mockup of this before we commit to it. I fear it will be very noisy.

**Comment by kevmoo** [comment]
Agreed.

**Comment by isoos** [comment]
This is being implemented as screenshots. #5092
